### ISSUE TITLE
Update - uif-table attribute validation

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#101]
The v0.2.0 will introduce two new directive guidelines, [007 & 008](https://github.com/ngOfficeUIFabric/ng-officeuifabric/blob/dev/docs/guides/DIRECTIVE-CHECKLIST.md#directive-attribute-validation), that address error message format & validating directive attributes with deterministic values (boolean, enum, number). Please update the directive to add error checking and ideally where appropriate, add an enum for set options. 

> You can see how `uif-icon` does this in the `dev` branch today for an example. The guideline doc also has an example of this.

Attributes to check for this directive:
- `uif-selected`
- `uif-orderasc` ??

**Comment by waldekmastykarz** [comment]
:+1:

**Comment by waldekmastykarz** [comment]
`uif-orderasc` is not an attribute that you can set on the directive. It's a property on the scope and it can only bet set through code where it's defined as boolean.
