### ISSUE TITLE
Update uif-spinner attribute name

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#102]
The attribute `uif-spinnersize` should really be `uif-spinner-size`. Can this get renamed & the demo updated?

**Comment by waldekmastykarz** [comment]
Since the directive is called `uif-spinner` and size is not a directive but a regular attribute how about we called it `uif-size` to keep it short and consistent with other attributes?

**Comment by andrewconnell** [comment]
Much better suggestion… make it so :)
