### ISSUE TITLE
Remove console.log from uif-contextual-menu

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#110]
When clicking on a menu item, a message is written to the console that's not necessary. This should be removed.

**Comment by s-KaiNet** [comment]
`console.log` is using only in demo - to demonstrate how you can attach `click` handler on menu, it's not used in contextual menu source. Should I really remove it? Or maybe replace in demo with `$log` service?

**Comment by andrewconnell** [comment]
Oh my bad... I thought it was coming from the library... fine as is. 

When doing a merge of a PR, I usually open the console to see if there are any errors... when I saw this, I just jumped to the conclusion. My bad.
