### ISSUE TITLE
Common namespace for enums

### ISSUE THREAD

**Issue by johnmeilleur** [ngOfficeUIFabric/ng-officeuifabric#116]
Looking at the various components I believe there will be some commonality with the enums.

For instance Persona and OrgChart will share enums like presence and style.

What does everyone think about putting them (or all enums for consistency) in either the core namespace or one dedicated for these datatypes?

**Comment by waldekmastykarz** [comment]
Could OrgChart reuse the Persona directive making it unnecessary to duplicate the enums?

**Comment by andrewconnell** [comment]
I've wondered the same thing like with the `IconEnum` that's in `uif-icon`. If `uif-org-chart` can depend on `uif-persona` for rendering and code reuse, then I say it stays with Persona. However if not and it's truly something that can be reused, I would put them in the root of the `officeuifabric.core` module.

FWIW, I've got a personal task to create enums in the `officeuifabric.core` for all color, animation & font size options. They would simply be used for developers to get strong naming of CSS classes. I think the color & animation ones are really the useful ones... font size won't get user much from code.

**Comment by andrewconnell** [comment]
Where does this stand @johnmeilleur ... reuse within existing directive or move to core?

**Comment by johnmeilleur** [comment]
Since they are really about the persona I agree as suggested we leave them in with the persona directive and other directives (e.g. orgchart) can reference as necessary.

**Comment by andrewconnell** [comment]
LGTM
