### ISSUE TITLE
Modify ConextualMenu to support more control over text

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#117]
I didn't notice this until we started looking at the spec for `uif-command-bar` but something occurred to me. The way the `uif-contextual-menu` control is done users have no control over the text in a menu item. Because the [text is defined in an attribute](https://github.com/ngOfficeUIFabric/ng-officeuifabric/blob/master/src/components/contextualmenu/demo/index.html#L70), you get what you get. However, what if someone wanted to have an icon prefix the text or change the color or weight of the font?

For the `uif-command-bar` we are [talking about wrapping this within a content element](https://github.com/ngOfficeUIFabric/ng-officeuifabric/issues/17#issuecomment-173825338) so that a user could change the color or add an icon. 

What do you guys think about this? Specifically the author of the directive, @s-KaiNet ?

**Comment by s-KaiNet** [comment]
You are not correct here. The text is actually `text: '=uifText'`, and following expression `uif-text="'Flag'"` is used just to pass a single string instead of relying on scope (for demo purposes).  
That means that you can use any text from scope, i.e. `scope.menuItem = 'My Item'` and `uif-text="menuItem"`

**Comment by s-KaiNet** [comment]
Sorry, misunderstood you. Reading through the command bar discussion I got the idea.  
This definitely can be done.

**Comment by andrewconnell** [comment]
Thoughts though? Is this a good idea? Definitely a breaking change, but is there value or am I just introducing more work?

**Comment by s-KaiNet** [comment]
I agree with the idea to support sub menus for command bar, also change to "Text" attribute looks very good, I'm completely for that. Created a [plunk](http://plnkr.co/edit/O5zgipEnv6bsBWmdAN8k?p=preview) with icons inside menu items and sub menu for command bar. IMHO looks cool.  
Some points to be considered:   
- UI Fabric sample doesn't include sub menu for the command bar. I guess they think that other components should be used for that, i.e contextual menu. In that case we are doing right thing 
- there is a small chance that UI Fabric team can change menu items elements (or css for elements) that can break everything, but I think this is a really small chance  
- on smaller devices menu collapsed with dots like on this [image](http://screencast.com/t/ObPhqHpphuY) by clicking component contextual menu shown.

**Comment by waldekmastykarz** [comment]
I wonder if such flexibility is what Office UI Fabric is meant for. Office UI Fabric introduces certain kind of design that imposes how the different pieces look like. Including icons would be a good idea: that's something that we already see in the command bar, but as for the text I would opt for plain-text rather than HTML.

**Comment by andrewconnell** [comment]
Love the plunk @s-KaiNet! Want to make this a feature of command menu? Agree on all three of the points you make above... while their samples may not show it, I don't see anything wrong with a submenu here.

**Comment by s-KaiNet** [comment]
Yep, I can do this or command menu author can add support. Actually nothing special - by clicking on command bar item you need to set `isOpen` for contextual menu and that's it.  
Not clear about changing `text` attribute. Should I go ahead and introduce possibility to provide enhanced text or not?

**Comment by andrewconnell** [comment]
Personally I think we should have that in the directive (enhanced text).

**Comment by s-KaiNet** [comment]
Can be closed because of #198
