### ISSUE TITLE
Support for required text fields is not a part of Office UI Fabric and should be removed

### ISSUE THREAD

**Issue by waldekmastykarz** [ngOfficeUIFabric/ng-officeuifabric#12]
Currently the TextField directive supports defining required fields (https://github.com/ngOfficeUIFabric/ng-officeuifabric/blob/544333a6bc2b004330e26d11f1968bb3fde01d97/src/components/textfield/textBoxDirective.ts#L24). This is however a custom implementation that isn't a part of Office UI Fabric.

As there are many different ways in how required fields can be marked in applications and there is no specification of it in Office UI Fabric, current implementation should be removed from the directive to stay aligned with Office UI Fabric.

**Comment by andrewconnell** [comment]
Agreed... for now let's have strict adherence to OOTB Office UI Fabric or if there's a common "required" visual indicator used in Office\* (O365 / clients / etc), let's implement that.

@rolandoldengarm is this something you want to address being your component?

**Comment by waldekmastykarz** [comment]
FWIW: looking at Fabric, the visual identification for required fields is implemented on Labels rather than on fields. See http://dev.office.com/fabric/components/label for an example of a Label for required field.

**Comment by ghost** [comment]
Yes, I will fix this. Please assign this issue to me @andrewconnell

**Comment by andrewconnell** [comment]
Addressed in pr #55
