### ISSUE TITLE
Callout - augment actions elements when uif-action-text used

### ISSUE THREAD

**Issue by jjczopek** [ngOfficeUIFabric/ng-officeuifabric#122]
When callout has `ms-Callout--actionText` class, action elements (links, buttons) have to be augmented with with additional CSS classes.

**Comment by andrewconnell** [comment]
Bug? Not sure I follow... What additional classes?

**Comment by jjczopek** [comment]
when `uif-action-text` is used, callout gets additional CSS class called `ms-Callout-actionText`. However it's not only the main callout element that should get the class. 

Also elements like buttons wrapped in `uif-callout-actions` should get additional CSS. Have a look at the [example](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/src/components/Callout/Callout.ActionText.html) from Fabric - buttons, and spans inside those buttons get `ms-Callout-action` and `ms-Callout-actionText` classes in additional to `ms-Callout-actionText` being added to the main callout div.

In issue #15 @waldekmastykarz  suggested that augmenting those classes should be responsibility of the callout rather than e.g. button responsibility to add those classes to avoid unnecessary dependencies.

**Comment by andrewconnell** [comment]
Ah... Ok. Is it a bug / feature then? Tagged correctly?

**Comment by jjczopek** [comment]
Classes are not added but should be, hence I think bug is fine.

**Comment by andrewconnell** [comment]
Manually merged to `dev`
