### ISSUE TITLE
Component to create: breadcrumb

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#13]
Official link to component description & demo: http://dev.office.com/fabric/components/breadcrumb

_Screenshot of web analytics for the original http://officeuifabric.com site by @andrewconnell. Use this to see what are the most popular components: http://imgur.com/gallery/buUcyQv_

**Comment by ghost** [comment]
My proposal for the specs:

```
<uif-breadcrumb uif-breadcrumb-current="Working files">
  <uif-breadcrumb-links>
    <uif-link ng-href="#">Title 1</a>
    <uif-link ng-href="#">Title 2</a>
    <uif-link ng-href="#">Title 3</a>
  </uif-breadcrumb-links>
</uif-breadcrumb>
```
- This limits the breadcrumb-current to be text. Thought that's fine, or should it be HTML content?
- This also doesn't allow to make the current item clickable, as per the demo on the Office UI Fabric.
- The directive should add the appropriate classes the uif-link (ms-Breadcrumb-parent)

Alternatively, to give more flexibility, we could do this:

```
<uif-breadcrumb>
  <uif-breadcrumb-current-large>
     <a href=#">Working files large now with a link</a>
  </uif-breadcrumb-current-large>
  <uif-breadcrumb-current>
     <a href=#">Working files now with a link</a>
  </uif-breadcrumb-current>
  <uif-breadcrumb-links>
    <uif-link ng-href="#">Title 1</a>
    <uif-link ng-href="#">Title 2</a>
    <uif-link ng-href="#">Title 3</a>
  </uif-breadcrumb-links>
</uif-breadcrumb>
```

Option 2 requires more HTML to implement for the developer.
Or, we could do both, option 3:

```
<uif-breadcrumb uif-breadcrumb-current-large="Working files large don't need a link">
  <uif-breadcrumb-current>
     <a href=#">Working files now with a link</a>
  </uif-breadcrumb-current>
  <uif-breadcrumb-links>
    <uif-link ng-href="#">Title 1</a>
    <uif-link ng-href="#">Title 2</a>
    <uif-link ng-href="#">Title 3</a>
  </uif-breadcrumb-links>
</uif-breadcrumb>
```

**Comment by waldekmastykarz** [comment]
What if current could be a property of a breadcrumb link?

``` html
<uif-breadcrumb>
  <uif-breadcrumb-links>
    <uif-breadcrumb-link ng-href="#">Title 1</a>
    <uif-breadcrumb-link ng-href="#">Title 2</a>
    <uif-breadcrumb-link uif-current="true" ng-href="#">Title 3</a>
  </uif-breadcrumb-links>
</uif-breadcrumb>
```

Another thing I wonder about is whether the text of breadcrumb-current-large is always the same as breadcrumb-current and with that could be derived from the link marked as current. If so it would simplify the directive's markup.

I would suggest using elements to have more flexibility, just as we do in other directives.

**Comment by ghost** [comment]
I was not sure if current-large is always the same as current. I would think so.
And I like your proposal with uif-current! Can't think of a disadvantage, unless current-large and current may be different.

**Comment by s-KaiNet** [comment]
I also prefer @waldekmastykarz approach.  
In that case `<uif-breadcrumb-links>` is redundant and can be skipped, imho. This simplifies things a bit. So only `<uif-breadcrumb>` at the root and `<uif-breadcrumb-link>` as links.

**Comment by waldekmastykarz** [comment]
That's even better @s-KaiNet! :smile:
