### ISSUE TITLE
Error when trying to install ngOfficeUIFabric from Bower

### ISSUE THREAD

**Issue by waldekmastykarz** [ngOfficeUIFabric/ng-officeuifabric#149]
When trying to install ngOfficeUIFabric from Bower you get the following error:

```
ng-office-ui-fabric is missing "main" entry in bower.json
```

Looking at the `bower.json` of ngOfficeUIFabric it indeed misses the `main` section

**Comment by andrewconnell** [comment]
Fixed... will be reflected in next update to the https://github.com/ngOfficeUIFabric/package-ngofficeuifabric project (anything greater than 0.3.0)

**Comment by waldekmastykarz** [comment]
Cool!
