### ISSUE TITLE
Invalid closing tag in spinner documentation

### ISSUE THREAD

**Issue by waldekmastykarz** [ngOfficeUIFabric/ng-officeuifabric#150]
On the spinner demo page at https://github.com/ngOfficeUIFabric/ng-officeuifabric/blob/806c8b63996ae8c12353fb09a69849938c1e1002/src/components/spinner/demo/index.html#L25 the closing tag in all examples should be `</uif-spinner>` rather than `<uif-spinner/>`.

**Comment by jjczopek** [comment]
Sure thing, I'll fix it.
