### ISSUE TITLE
When programmatically setting the value of the textfield with a placeholder, the placeholder label doesn't disappear

### ISSUE THREAD

**Issue by waldekmastykarz** [ngOfficeUIFabric/ng-officeuifabric#152]
When you update the value of the model assigned to a textfield with placeholder, the placeholder label doesn't disappear and is displayed on top of the textfield value.

See this plunk for a demo of this issue: http://plnkr.co/edit/QCDPHguqGzJaznLYiRP9?p=preview

**Comment by andrewconnell** [comment]
Good find... def. a bug.

**Comment by waldekmastykarz** [comment]
:+1:

**Comment by ghost** [comment]
This will require an update to the test scripts as well, this should be verified as part of the test that sets the placeholder.

**Comment by ghost** [comment]
Please assign to me :)
