### ISSUE TITLE
When using a textfield with placeholder clicking on the placeholder prevents from setting the focus

### ISSUE THREAD

**Issue by waldekmastykarz** [ngOfficeUIFabric/ng-officeuifabric#154]
When using a textfield with a placeholder, the only way to set the focus on the textfield is to click next to the placeholder. Clicking on the placeholder prevents the focus from being set on the textfield.

See this plunk for a demo of this issue: http://plnkr.co/edit/QCDPHguqGzJaznLYiRP9?p=preview

**Comment by ghost** [comment]
Verified that it happens in the demo as well.

It also happens in the example on the OfficeUIFabric: http://dev.office.com/fabric/components/textfield
It is a bit different; if you click on the placeholder, it disappears, but the focus is not in the textfield.

**Comment by andrewconnell** [comment]
Agreed @rolandoldengarm ... you want this?

**Comment by andrewconnell** [comment]
RE "happens in OfficeUIFabric"

In that case it should be bugged in the Office UI Fabric repo... let's confirm if this is a bug in Fabric / not. If so, let them fix it. If not, we fix it. just like #151.

@waldekmastykarz since you found, you want to log it in Office UI Fabric (same way you did with spinner's #151)?

**Comment by waldekmastykarz** [comment]
Given that the script files included with Office UI Fabric are samples is it fair to say that it's an Office UI Fabric bug or is it rather a bug that we took over when building our own scripts and which we should fix in our code?

**Comment by andrewconnell** [comment]
Doh… good point… that’s defiantly a bug then on our part and we should fix it as that’s functionality we created.

**Comment by ghost** [comment]
Please assign to me, I'll fix it in our scripts :)

**Comment by andrewconnell** [comment]
Appears this has been identified as a bug in fabric (https://github.com/OfficeDev/Office-UI-Fabric/issues/316) ... so should we address it?

**Comment by ghost** [comment]
Hmm, I thought it would require a script fix, e.g. when clicking on the placeholder, set focus on the textbox.
But apparently it is fixable in CSS only.

Shall we wait for the OfficeUIFabric fix?

**Comment by waldekmastykarz** [comment]
If they say they are going to fix it would be a waste of effort to do it ourselves. +1 to wait for the fix.

**Comment by jjczopek** [comment]
:+1:

**Comment by andrewconnell** [comment]
Taking this off our work item list... moving to backlog as we'll let fabric fix it. Less code for us to write & maintain.

**Comment by ghost** [comment]
I'm closing this as this has been fixed in latest release of Office UI Fabric. Please open a new bug if issue still exists.
