### ISSUE TITLE
jQuery.noconflict should be removed from tests

### ISSUE THREAD

**Issue by ghost** [ngOfficeUIFabric/ng-officeuifabric#156]
choicefieldDirective and dropdownDirective specs contain jQuery noconflict.
This causes weird behavior together with live-dev, as in that case jQuery will be loaded as $. But when running ALL tests, $ is undefined.

So, it should be removed from specific tests, and either be removed entirely, or put in core.ts / base test file which is always run. I'd vote for removal, need to double check that that does not impact current tests, i.e. does jQuery still work without noconflict.

**Comment by andrewconnell** [comment]
A quick search shows `noconflict()` is in just those two directive's specs. Assume this is something you'll address with them since they are yours @rolandoldengarm?

If so, fair to bug it & assign to you?

**Comment by ghost** [comment]
Yes please.

**Comment by ghost** [comment]
Already submitted a PR :) https://github.com/ngOfficeUIFabric/ng-officeuifabric/pull/158
