### ISSUE TITLE
Move "files" configuration settings for karma to build.ts

### ISSUE THREAD

**Issue by s-KaiNet** [ngOfficeUIFabric/ng-officeuifabric#157]
Currently some configuration settings (`files`) for karma used in two different places (in karma.ts config and in gulp live-dev task). Some time it's necessary to add new files for config and this should be done in one place.  
That's why configuration setting for files, which are common (i.e. `node_modules` and phantomjs fix), should be included in common well-known place like `build.ts`.

**Comment by andrewconnell** [comment]
Once the `uif-button` is finished, I have some chore work with our build & docs process... I can include this in that work so I can grab it.

**Comment by s-KaiNet** [comment]
ok, thanks.
