### ISSUE TITLE
Feature: Create Service for Dialog 

### ISSUE THREAD

**Issue by jigargandhi** [ngOfficeUIFabric/ng-officeuifabric#159]
Dialog component on its own is of little use. Angular material provides [$mdDialog](https://material.angularjs.org/latest/api/service/$mdDialog) service that helps in creating dialogs with various configuration. 

An angular service `$uifDialog` needs to be created that provides functionality to create dialogs on the fly.
/cc: @andrewconnell @ngOfficeUIFabric/ngofficeuifabric-members

**Comment by jigargandhi** [comment]
# Methods

$uifDialog.alert()

$uifDialog.confirm()

$uifDialog.prompt()

$uifDialog.show()

$uifDialog.hide()

$uifDialog.cancel()

The parameters of these functions can be similar to $mdDialog

@andrewconnell: Let me know if more detailing is required /cc: @ngOfficeUIFabric/ngofficeuifabric-collaborators

**Comment by andrewconnell** [comment]
IDK... I think I'd personally like to see more usage of what this would look like from a controller to be sold on this service. Then again, it's an enhancement & I get why MD has it... so if you want to tackle it, I say go for it @jigargandhi

**Comment by andrewconnell** [comment]
But... need to see more of a spec before you go building so we can all agree :)

**Comment by andrewconnell** [comment]
Closing... see #455
