### ISSUE TITLE
Component to create: choicefield

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#16]
Official link to component description & demo: http://dev.office.com/fabric/components/choicefield

_Screenshot of web analytics for the original http://officeuifabric.com site by @andrewconnell. Use this to see what are the most popular components: http://imgur.com/gallery/buUcyQv_

**Comment by andrewconnell** [comment]
~~Originally submitted by @rolandoldengarm, but needs some additional work:~~
- [x] ~~converted from an attribute => element directive~~
- [x] ~~add support & examples for checkbox~~
- [x] ~~add support for placeholder~~
- [x] ~~add support for underline~~
- [x] ~~add more robust docs to directive~~

**Comment by ghost** [comment]
@andrewconnell The todo items here were for the textfield component :) 
Specs:

```
<uif-choicefield-group uif-choicefield-type="radio|checkbox" uif-choicefield-title="Title">
  <uif-choicefield-option value="Value1">Text 1</uif-choicefield-option>
  <uif-choicefield-option value="Value2" disabled>Text 2</uif-choicefield-option>
</uif-choicefield>
```

**Comment by andrewconnell** [comment]
Arg... good point... nixed those.

What about just a stand alone one... would it simply be (no group wrapping)?

```
<uif-choicefield-option value="Value1">Text 1</uif-choicefield-option>
```

**Comment by ghost** [comment]
Yes, it is possible to use it stand-alone. There is a ?^dependency on uif-choicefield-group.
