### ISSUE TITLE
missing sample markup in uif-button demo

### ISSUE THREAD

**Issue by jjczopek** [ngOfficeUIFabric/ng-officeuifabric#185]
Demo page for [`uif-button`](https://github.com/ngOfficeUIFabric/ng-officeuifabric/blob/master/src/components/button/demo/index.html) directive is missing sample markup - it contains only rendered output. 

In order to see how specific output has been achieved, one has go to the source of the page.

**Comment by andrewconnell** [comment]
Arg... how did I miss that. Thanks... I'm on it.
