### ISSUE TITLE
missing hero type in uif-link component

### ISSUE THREAD

**Issue by jjczopek** [ngOfficeUIFabric/ng-officeuifabric#187]
Fabric UI for the link component has two modes:
- regular: [Link.html](https://github.com/OfficeDev/Office-UI-Fabric/tree/master/src/components/Link)
- hero: [Link.Hero.html](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/src/components/Link/Link.Hero.html)

Currently our `uif-link` component is missing the hero type:
- `uif-type` attribute
- enum specifying available values
- validation of the type

**Comment by tdwhite0** [comment]
Acknowledged, I'll get this updated

**Comment by tdwhite0** [comment]
Someone else should take this. I won't be able to put the effort in to do this the way the project requires.

**Comment by jjczopek** [comment]
let me work on that - some change from persona card would be good for me ;)

**Comment by andrewconnell** [comment]
Looks like Fabric might be going back on this one... https://github.com/OfficeDev/Office-UI-Fabric/issues/338#issuecomment-188995779

**Comment by andrewconnell** [comment]
Yup... they backed it out... we need to remove the hero type of link out - https://github.com/OfficeDev/Office-UI-Fabric/pull/395

**Comment by jjczopek** [comment]
crazy. I'll take of it if I find a spare moment

**Comment by andrewconnell** [comment]
Took care of it...
