### ISSUE TITLE
Build doesn't fail in Travis if any vet errors

### ISSUE THREAD

**Issue by s-KaiNet** [ngOfficeUIFabric/ng-officeuifabric#192]
For `tslint` task setting `emitError: false` was added to prevent breaking pipeline for `live-dev` task.  
In this case Travis build doesn't fail and shows green state.  
Proposed solution:  
Leave it as is for "regular" tasks, but add additional param for travis, so in travis config it will be something like this `gulp vet-lib-ts --verbose --emitError`

**Comment by andrewconnell** [comment]
I can take this on in my build updates i'm working on as this is tightly related to #170... cool? if you agree, feel free to reassign to me

**Comment by s-KaiNet** [comment]
Cool! :)
