### ISSUE TITLE
ContextualMenu - improvements, refactoring, fixing issues

### ISSUE THREAD

**Issue by s-KaiNet** [ngOfficeUIFabric/ng-officeuifabric#198]
I want to consolidate here all work which is might be required for contextual menu and waiting for your approval. I didn't create a spec for contextual menu in the past, so I'm correcting mistake right now:  
### `Contextual menu spec:`

``` html
<uif-contextual-menu uif-is-open="isOpen" uif-multiselect="true|false" uif-close-on-click="false|true">
  <uif-contextual-menu-item uif-text="'Tools'" uif-type="subMenu|link|divider|header" 
                            uif-click="logClick('Tools clicked!')"
                            uif-is-selected="true|false" uif-is-disabled="true|false">
  </uif-contextual-menu-item>
</uif-contextual-menu>
```

`<uif-contextual-menu>`:
- `@uif-is-open` - controls state of the menu
- `@uif-close-on-click` - controls if menu should be closed after clicking, default is true
- `@uif-multiselect` - `true` for multi selection menu, default `false`  

`<uif-contextual-menu-item>`:  
- `=uif-text` - text for menu item
- `=uif-is-disabled` - controls disabled state
- `=uif-is-selected` - controls selected state
- `@uif-type` - menu type, default `link`
- `&uif-click` - click handler  
### Proposed changes:
1. remove `uif-click` and rely on `ng-click` instead [link](https://github.com/ngOfficeUIFabric/ng-officeuifabric/issues/26#issuecomment-182325069)
2.  rename `uif-is-disabled` to simply 'disabled' [link](https://github.com/ngOfficeUIFabric/ng-officeuifabric/issues/26#issuecomment-178853924)
3. add new directive `<uif-context-item-content>` to more control over text, like in navbar directive. [link](https://github.com/ngOfficeUIFabric/ng-officeuifabric/issues/117) and [link](https://github.com/ngOfficeUIFabric/ng-officeuifabric/issues/136). For this one what I'm thinking about is creating separate directive `<uif-content>` or something and use it in both contextual menu and navbar.  
4. Your proposals.

**Comment by andrewconnell** [comment]
Sorry I missed this... I really like all the proposed changes.

**Comment by waldekmastykarz** [comment]
:+1:
