### ISSUE TITLE
Component to create: dialog

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#20]
Official link to component description & demo: http://dev.office.com/fabric/components/dialog

_Screenshot of web analytics for the original http://officeuifabric.com site by @andrewconnell. Use this to see what are the most popular components: http://imgur.com/gallery/buUcyQv_

**Comment by jigargandhi** [comment]
Thought could work on this one.. require help with specs before I get started

**Comment by andrewconnell** [comment]
All you @jigargandhi! Take a look at how we did the specs for table #36 & button #14 as examples for the specs... but let's have the convo here and if you want to draw attention to get folks to chime in, post something to slack to get them to come here and comment

**Comment by jigargandhi** [comment]
Spec:
 **Dialog**

```
 <uif-dialog uif-type="<empty>|header|multiline" uif-close="true|false" uif-overlay="light|dark">
       <uif-dialog-header>
                  <uif-dialog-title> </uif-dialog-title>
           </uif-dialog-header>
           <uif-dialog-content>
                  <uif-dialog-subtext> </uif-dialog-subtext>
           </uif-dialog-content>
       <uif-dialog-actions uif-position="left|right" >
                     <uif-button />
          </uif-dialog-actions>
 </uif-dialog>
```

**Update** Modified as per [comment](https://github.com/ngOfficeUIFabric/ng-officeuifabric/issues/20#issuecomment-171882589) from @waldekmastykarz 

**Update 2** included overlay in the spec

**Update 3** added uif-close as a separate attribute

**Comment by waldekmastykarz** [comment]
Since the dialog types are exclusive what if we would do: `uif-type="close|header|multiline"`. Since the `uif-type` is not a directive, we don't need to include the `dialog` part in it which will keep it shorter.

One thing that I think it's missing in the spec is the overlay which is include in dialog's HTML.

Another thing that I'm wondering about is the `subtext` part. In the current spec how would we distinguish between what should go in `subtext` and what should be outside (if you look at the close dialog sample you see that the text paragraph is wrapped in `subtext` while checkboxes aren't. In the spec you suggested we can only add content which doesn't distinguish between the two pieces)?

**Comment by andrewconnell** [comment]
Agree with @waldekmastykarz 100% on all three points.

RE `uif-type`... the way the spec is originally written mirrors the CSS classes in fabric... we want to get away from that.

**Comment by jigargandhi** [comment]
I have updated the specs with `title` and `subtext`
I do not get the purpose of the `overlay` empty div in the sample site. As removing it does not change the UI
If anyone has any better idea please comment.

**Comment by waldekmastykarz** [comment]
Isn't it supposed to grey out the page while showing the dialog?

**Comment by jigargandhi** [comment]
try this:
- Go to dialog sample page http://dev.office.com/fabric/components/dialog
- Open chrome developer tools
- inspect the dialog element
- delete the node `<div class='ms-Overlay'></div>`
- See that nothing happens

**Comment by waldekmastykarz** [comment]
Overlay is defined as a separate component, take a look at http://dev.office.com/fabric/components/overlay. If you look closely at the samples you see that it uses separate CSS which perhaps aren't properly included in the dialog sample. I would suspect that the way it's supposed to be working is shown in the Overlay sample and we should try to get the same result in the dialog component.

**Comment by jigargandhi** [comment]
You were right @waldekmastykarz, I had to include the components file in the sample to see the overlay effect. 

I have updated the spec with `uif-overlay` attribute which will default to `light`.

If @ngOfficeUIFabric/ngofficeuifabric-members agree and finalize the spec then I can start developing it.

**Comment by s-KaiNet** [comment]
For me all good, but I would divide `close` as separate attribute `uif-close=true|false`. For example, what if I want multiline with close button?  
Close button `<button class="ms-Dialog-button ms-Dialog-button--close">` presents in all types of dialogs and can be visible by including `ms-Dialog--close` class. However it's not visible for large header (explicitly hidden by fabric's css).   

Taking this into account top part of the directive will looks like:  
`<uif-dialog uif-close="true|false" uif-type="<empy>|header|multiline" uif-overlay="light|dark">`   

`uif-type` `<empy>` means that without attribute "regular" dialog will be rendered - `<div class="ms-Dialog">`, `uif-close=true` simply adds `ms-Dialog--close` class (but will not be visible for `uif-type=header` like I mentioned above, will be visible for all other types).  

**UPD** Should we create separate overlay directive? It used by navbar as well.

**Comment by jigargandhi** [comment]
Good find @s-KaiNet , have update the specs to reflect the same. 

@andrewconnell I think the current specs are good to go for development

**Comment by andrewconnell** [comment]
LGTM... you guys seem to cover lot of bases...

**Comment by andrewconnell** [comment]
Touching base... how's it going with the directive?

**Comment by jigargandhi** [comment]
you can see status at my [fork-branch](https://github.com/jigargandhi/ng-officeuifabric/tree/issue20-dialog)

**Comment by andrewconnell** [comment]
Awesome... thanks! Just making sure it was still being worked on since we hadn't seen a PR or heard anything.

**Comment by ranjit-singh** [comment]
there is no close event for dialog. is anyone knows that how to close dialog?

**Comment by sandves** [comment]
I also want to know how to close the dialog without using ng-show and a custom button.
