### ISSUE TITLE
REQ INPUT - Rewrite our commit history

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#207]
Over the last month+ I have been tweaking commit messages for PRs to match a specific syntax that the Angular Material team uses. In the latest push this morning that I just merged, I've updated our docs to reflect this: [https://github.com/ngOfficeUIFabric/ng-officeuifabric/blob/master/docs/guides/CODING.md#commit-messages](commit-messages). 

Why do this? I think the reasons are simple... so our commit log is clean & easy to consume... something that looks like this...

![ngofficeuifabric-keepingcleancommitlog-02](https://cloud.githubusercontent.com/assets/2068657/13426181/d82d8eda-df79-11e5-80ab-28a55197a9eb.png)

... is much more useable than this ...

![ngofficeuifabric-keepingcleancommitlog-04](https://cloud.githubusercontent.com/assets/2068657/13426186/e0b1ae60-df79-11e5-9ed2-ccfd98a79dd8.png)
### This Matters Because...

Not only is it readable, but it will also act as our documentation for changes. There are tools we can run that will dynamically generate the change log with links & suck in things like breaking changes, referencing the specific commit where the change occurred. It's a better world (and it's one that Angular Material uses).
### The Challenge...

... is that we didn't start out this way... the first ~70 commits didn't use this format... they were just haphazard (most of them were me). In addition, there are some recent commits that don't follow this... typos in the scope & type, etc...

So we are in a bit of flux...
### I PROPOSE (_and want your input_)...

I think we will benefit from this. **I can rewrite the history which simply means I'll update the commit messages we currently have in the commit log**. The only commits I'd like to squash to a single commit are mine from back in the start of this project (_stuff [like this is not necessary](https://github.com/ngOfficeUIFabric/ng-officeuifabric/commit/2d9159b4fda94edb996d0d00b39ed123c65d8b3b) in it's own commit... it should have been squashed_).

To be clear, I'm proposing that I do this, but want to make sure everyone has a voice.
### What Are The Implications?

There are two:
- [ ] anyone with a fork will need to rebase their fork on upstream (I can provide instructions on how to do this when we make this commit) or you can do the easy thing: delete your fork, your local clone, re-fork & re-clone the new fork.
- [ ] any references to specific commits may change... for instance a reference to a commit from an issue will now get duped
  - this is because the SHA of the commit will change when the commit changes... so the old link may break to the old SHA, but because the reference to the issue within the commit is still there, the link will get re-added

If we don't do this we likely won't be able to have dynamically generated changelog and have some inconsistencies in our history; not ideal, but not the end of the world either.
### What Say You?
- [x] YES, go ahead and rewrite the commit history
- [ ] NO, don't do this... leave it as is

**Comment by jjczopek** [comment]
I'm supportive

**Comment by s-KaiNet** [comment]
If **you** will do that, I'm for this. But personally I don't see much value. Just +1 to perfection for the project, doesn't it?

**Comment by andrewconnell** [comment]
@s-KaiNet correct, I'll do it. You guys can just sit back and wait for me to say "rebase your `master` and `dev` branches by running these commands"

**Comment by ghost** [comment]
YES. Better do it now than in the future, and it will make release management easier.

**Comment by andrewconnell** [comment]
LGTM... no objections so I'll tackle it in the near future.

**Comment by waldekmastykarz** [comment]
:+1:

**Comment by andrewconnell** [comment]
This isn't going to happen... as much as I'd love to have a pristine commit log going back to the start, it has too many pitfalls to as every single SHA1 will get updated.
