### ISSUE TITLE
Check Fabric 2.1.0 Reelease

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#209]
Look at the recent fabric 2.1.0 release for updates that affect us

**Comment by andrewconnell** [comment]
- [ ] fabric v2.1.0 includes fix for pickadate.js latest version... we can update dependencies to use latest pickadate.js

**Comment by ghost** [comment]
I could do it, but the check is fairly simple: Go to the demo and open multiple date pickers at the same time and verify there is no overlap.

**Comment by andrewconnell** [comment]
No worries… I got it… part of the next release.
