### ISSUE TITLE
Component to create: dropdown

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#21]
Official link to component description & demo: http://dev.office.com/fabric/components/dropdown

_Screenshot of web analytics for the original http://officeuifabric.com site by @andrewconnell. Use this to see what are the most popular components: http://imgur.com/gallery/buUcyQv_

**Comment by andrewconnell** [comment]
Started by @rolandoldengarm

**Comment by ghost** [comment]
I already implemented this, but it was too restrictive we've found. So I'm refactoring it but that takes quite some time. 
Work in progress.

**Comment by CodeMoggy** [comment]
Hi Rolando...do you have a spec on what you are planning to implement? Thanks

**Comment by ghost** [comment]
@CodeMoggy I'm going to implement it similar to Angular material. So, a <uif-select> "main" element and <uif-option> child elements. Full spec to follow.

**Comment by ghost** [comment]
Okay, the full spec:

```
<uif-dropdown ng-model='scopeProp' disabled>
   <uif-option ng-repeat='option in options' ng-value='option.value'>{{option.text}}</uif-option>
<uif-dropdown>
```

That's about it I think, agreed? What do you think @CodeMoggy @andrewconnell

**Comment by andrewconnell** [comment]
:+1: LGTM
