### ISSUE TITLE
Component to create: label

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#22]
Official link to component description & demo: http://dev.office.com/fabric/components/label

_Screenshot of web analytics for the original http://officeuifabric.com site by @andrewconnell. Use this to see what are the most popular components: http://imgur.com/gallery/buUcyQv_

**Comment by jjczopek** [comment]
I'm picking up this one.

Please have a look at the specs:

**Standard label:**
`<uif-label>Name</uif-label>`

**Required:**
`<uif-label required>Required name</uif-label>`

**Disabled:**
`<uif-label disabled>Disabled name</uif-label>`

`required` and `disabled` are well-known HTML attributes, therefore I assume there is no need in prefixing them with `uif-`.

**Comment by andrewconnell** [comment]
LGTM... go for it
