### ISSUE TITLE
uifClose Button type attribute is not defined in calloutDirective

### ISSUE THREAD

**Issue by reifi** [ngOfficeUIFabric/ng-officeuifabric#221]
uif-close button should have a defined type attribute value: _type="button"_. 
If not set, its default value is _type="submit"_. This is the default if the attribute is not specified, or if the attribute is dynamically changed to an empty or invalid value.

So should have all other form independent buttons.

`<button class="ms-Callout-close">`
### Expected

`<button class="ms-Callout-close" type="button">`

No HTML5 form is submitted when used inside `<form/>`
### Actual

`<button class="ms-Callout-close">`

HTML5 Form gets submitted because of close button when callout is inside `<form/>`

See https://github.com/ngOfficeUIFabric/ng-officeuifabric/blob/master/src/components/callout/calloutDirective.ts#L273

and

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

**Comment by andrewconnell** [comment]
Can you elaborate more on this?

From my POV and experience, when building Angular apps, you don’t want to submit a form, rather when a button is clicked you handle it within the controller.

**Comment by reifi** [comment]
(I'm using Angular 1.5)
https://docs.angularjs.org/api/ng/directive/form#submitting-a-form-and-preventing-the-default-action

First of all, ngSubmit should handle the submit. 
The user should be allowed to choose how the form submit is triggered: With multiple submit buttons, by ngclick on certain elements or by programmatical form.submit()

If the user chooses to submit by ngSubmit, your uif-close button will trigger it when its HTML is inside a form because the default action is "submit". 

Well, it's not a submit button, so it needs a type attribute saying it's not having the HTML5 button's default type which is 'submit'. (See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button)

**Comment by andrewconnell** [comment]
Thanks for the additional detail…

So are you proposing that the generated button should include a `type=“button”` then, or offer an option for the developer using the directive to specify the button type? As I understand it now, in v0.6.0 the callout’s close button is assumed to be `type=submit`… but, again if I understand you correctly, if we render `type=button` then the user doesn’t have any control.

Would they need it? Why?

**Comment by andrewconnell** [comment]
Looping original dev on this thread

/cc: @jjczopek

**Comment by jjczopek** [comment]
I think what @reifi suggest makes sense, as the default behaviour of button might cause confusion and unnecessary submissions when not expected. The close button on the callout is there only for letting user to close the callout, and I don't think there is any additional control needed or expected behaviour on this element. I'm supportive of the fix for adding the `type="button"` and I can handle it.

Apart from the close button, users can have their own buttons as callout directives are transcluding content as-is. Those buttons can implement any kind of logic depending on the needs.

**Comment by andrewconnell** [comment]
OK... I'll update the tags and leave it as ready for dev... if you want it feel free to claim.
