### ISSUE TITLE
Dropdown & Choicefield suggestions / issues

### ISSUE THREAD

**Issue by oviava** [ngOfficeUIFabric/ng-officeuifabric#222]
Choicefield: 
- multi select option for checkboxes 

Dropdown
- placeholder text when nothing is selected
- provide an option to pass a callback on item select:

``` html
<uif-dropdown ng-model="selectedItem" handleSelect="myOwnFunction">
...
</uif-dropdown>
```

**Comment by andrewconnell** [comment]
Looping original owner of these to get their input as they are most familiar with the directives.

/cc: @rolandoldengarm

**Comment by ghost** [comment]
**Choicefield multi select:**
You can just add multiple uif-choicefield-option elements? Have you tried that? 

**Dropdown placeholder:**
The way this works now, is that you need to add an option with an empty value. 

**Dropdown handleSelect:**
Can you please elaborate what you're trying to achieve? Can't you achieve this by attaching an ng-click event to the uif-dropdown-option?
If we're going down the path of adding events, we'll need to look at all our directives @andrewconnell

**Comment by rolandoldengarm** [comment]
@oviava Could you please reply to my comments?

**Comment by ghost** [comment]
Closing this due to no reply. Please raise an issue if you still feel there is a bug or a feature request. Please separate them into one issue per request / feature.
