### ISSUE TITLE
TextField does not support multiline or change of input type

### ISSUE THREAD

**Issue by florinszilagyi** [ngOfficeUIFabric/ng-officeuifabric#227]
The uif-textfield directive should have multiline support, and also allow the specification of the type. (Eg. a password field)

**Comment by ghost** [comment]
Makes sense, yes.
The code changes in the PR look good to me (https://github.com/ngOfficeUIFabric/ng-officeuifabric/pull/226). Please fix the issues raised there and submit another PR.
