### ISSUE TITLE
Dropdown - initial value not selected

### ISSUE THREAD

**Issue by jjczopek** [ngOfficeUIFabric/ng-officeuifabric#230]
### Expected Behavior

When dropdown is bound to a model which is intially set, and options are rendered via ng-repeat, I would expect that option that is corresponding to the initial value of model is pre-selected:
![image](https://cloud.githubusercontent.com/assets/865473/13722475/7c055efe-e847-11e5-99a7-abd8d06918bb.png)
### Actual Behavior

When model is initially set, there is nothing selected in the dropdown:
![image](https://cloud.githubusercontent.com/assets/865473/13722470/65aaf63c-e847-11e5-8890-2b597c6b1f07.png)

It is reproduced in the following codepen:
http://codepen.io/jjczopek/pen/VaKZJY
### Steps to Reproduce Behavior

See above codepen.

@rolandoldengarm: I think you would know the best ;)

**Comment by ghost** [comment]
Yes, looks like a bug to me. Will work on it.

**Comment by ghost** [comment]
I've spent quite some time on it, but haven't been able to find a solution. 
During link, the render function of ngModel is called and tries to retrieve the child elements to find the element with the given value. However, at that time the elements are not compiled yet.
I've tried different things, and fixed it partly. However, it's still not working when ng-repeat is used.
The demo is working as that one is not using ng-repeat.
See my branch here: https://github.com/rolandoldengarm/ng-officeuifabric/tree/issue-230

It's time for a fresh pair of eyes to have a look.

**Comment by waldekmastykarz** [comment]
One workaround would be to pass the value using the `title` attribute. Since attributes are bound at the time of the execution of the postLink function you can use the value from the `title` attribute to update the selected item. I have a working solution in my fork @ https://github.com/waldekmastykarz/ng-officeuifabric/tree/issue-230. Looking forward to hear your thoughts on this approach.

**Comment by ghost** [comment]
That looks good to me, thanks. That was easy... Will you be able to add a test case, as I've added to proof it's working?
I can't clone your repo, as I've already cloned the main repo.

See [here](https://github.com/rolandoldengarm/ng-officeuifabric/blob/b6bf1d32a8922d11d8c32adb0b1bb6d8e3d323ed/src/components/dropdown/dropdownDirective.spec.ts) for the test case:

```
it('should be able to set initial value', inject(($compile: Function, $rootScope: ng.IRootScopeService) => {
        let $scope: any = $rootScope.$new();
        $scope.options = [
            { text: 'Option 1', value: 'Option1'},
            { text: 'Option 2', value: 'Option2'},
            { text: 'Option 3', value: 'Option3'},
            { text: 'Option 4', value: 'Option4'}
        ];
        $scope.selectedValue = 'Option2';
        let dropdown: JQuery = $compile('<uif-dropdown ng-model="selectedValue">' +
            '<uif-dropdown-option ng-repeat="o in options" value="{{o.value}}">{{o.text}}</uif-dropdown-option></uif-dropdown>')($scope);

        $scope.$digest();
        dropdown = jQuery(dropdown[0]);
        let title: JQuery = dropdown.find('span.ms-Dropdown-title');
        expect(title.text()).toBe('Option 2', 'Displayed text should be Option 2');
    }));
```

**Comment by waldekmastykarz** [comment]
Will do that!

**Comment by waldekmastykarz** [comment]
I've added the test. Do you mind checking it out @rolandoldengarm?

**Comment by ghost** [comment]
@waldekmastykarz I don't see a commit to that branch?
https://github.com/waldekmastykarz/ng-officeuifabric/commits/issue-230

**Comment by waldekmastykarz** [comment]
I've amended the previous commit.

**Comment by ghost** [comment]
Ah :)
Yes, looks good to me!! Please submit a PR :)
