### ISSUE TITLE
Incorrect files built

### ISSUE THREAD

**Issue by ghost** [ngOfficeUIFabric/ng-officeuifabric#233]
Unless I'm misunderstanding the intention of the `--debug` switch on the build commandline, I think the wrong files are being built when you issue the command `gulp build-lib --debug`.  This produces the minified version of ngOfficeUiFabric.js (ngOfficeUiFabric.min.js) which isn't what is expected by the demo pages, and doesn't seem right - you don't want minified in a dev build.

The fix is easy: just swap lines 60 and 64 of build-lib.ts and regenerate the .js build files from the .ts

**Comment by jjczopek** [comment]
If I remember correctly, there have been updates to the build process. In order to build version of the library for demos, use the following command: `gulp build-lib --dev`.

Probably docs need to be updated.

**Comment by ghost** [comment]
`--dev` did the trick, so just a documentation bug in the MPA.md doc.  Thanks.

**Comment by ghost** [comment]
Requires documentation update.
