### ISSUE TITLE
Component to create: list

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#24]
Official link to component description & demo: http://dev.office.com/fabric/components/list

_Screenshot of web analytics for the original http://officeuifabric.com site by @andrewconnell. Use this to see what are the most popular components: http://imgur.com/gallery/buUcyQv_

**Comment by waldekmastykarz** [comment]
Shall I take this one? List doesn't do much on its own other than setting layout either as a list or grid. I know Office UI Fabric shows ListItem as a separate component but shouldn't we combine #24 with #25?

**Comment by andrewconnell** [comment]
Shouldn’t the table get finished off with the functionality we want to add? I thought that was the whole discussion was that we could have multiple releases of the table, but we’d get to the point where we had sortable columns & selectable rows?

**Comment by waldekmastykarz** [comment]
I thought we wanted to get p1 across the suite done first and then start extending the specific components with new capabilities. That way devs could use more components (even if with less functionality) rather than having only a few fully baked ones. It would also make it easier for other folks to jump in and help with specific features rather than having to build a complete directive.
Either way I'm happy to continue with selecting rows and sorting columns :)

**Comment by andrewconnell** [comment]
Personally I think we want to knock one out before we move on to the next one. When we were talking about P1, P2 etc, in my mine I was thinking only about the table component.

**Comment by waldekmastykarz** [comment]
:+1:

**Comment by waldekmastykarz** [comment]
How about we do it like this:
- [x] list supports two layout modes _list_ (default) and _grid_
- [x] list supports three modes for selecting items: _none_ (default), _single_ and _multiple_
- [x] list supports three ways for rendering items: _item_ (default), _itemWithImage_ and _itemWithIcon_
- [x] specific item types might require additional directives
  - [x] regular = no additional directives required
  - [x] item with image require the `uif-list-item-image` directive
  - [x] item with icon require the `uif-list-item-icon` directive
- [x] if required directives are missing an error is thrown

``` html
<uif-list uif-layout="list|grid" uif-item-select-mode="none|single|multiple">
  <uif-list-item ng-repeat="message in vm.messages" uif-unread="{{message.isUnread}}" uif-unseen="{{message.isUnseen}}" uif-selected="{{message.isSelected}}" uif-type="item|itemWithImage|itemWithIcon">
    <uif-list-item-primary-text>{{message.sender.name}}</uif-list-item-primary-text>
    <uif-list-item-secondary-text>{{message.title}}</uif-list-item-secondary-text>
    <uif-list-item-tertiary-text>{{message.description}}</uif-list-item-tertiary-text>
    <uif-list-item-meta-text>{{message.time}}</uif-list-item-meta-text>
    <uif-list-item-actions>
      <uif-list-item-action ng-click="vm.mail(message)">
        <uif-icon uif-type="mail" />
      </uif-list-item-action>
      <uif-list-item-action ng-click="vm.delete(message)">
        <uif-icon uif-type="trash" />
      </uif-list-item-action>
      <uif-list-item-action ng-click="vm.delete(message)">
        <uif-icon uif-type="pinLeft" />
      </uif-list-item-action>
    </uif-list-item-actions>
  </uif-list-item>
</uif-list>
```

## Grid list:

``` html
<uif-list uif-layout="grid">
  <uif-list-item ng-repeat="message in vm.messages" uif-unread="{{message.isUnread}}" uif-unseen="{{message.isUnseen}}" uif-selected="{{message.isSelected}}">
    <uif-list-item-primary-text>{{message.sender.name}}</uif-list-item-primary-text>
    <uif-list-item-secondary-text>{{message.title}}</uif-list-item-secondary-text>
    <uif-list-item-tertiary-text>{{message.description}}</uif-list-item-tertiary-text>
    <uif-list-item-meta-text>{{message.time}}</uif-list-item-meta-text>
    <uif-list-item-actions>
      <uif-list-item-action ng-click="vm.mail(message)">
        <uif-icon uif-type="mail" />
      </uif-list-item-action>
      <uif-list-item-action ng-click="vm.delete(message)">
        <uif-icon uif-type="trash" />
      </uif-list-item-action>
      <uif-list-item-action ng-click="vm.delete(message)">
        <uif-icon uif-type="pinLeft" />
      </uif-list-item-action>
    </uif-list-item-actions>
  </uif-list-item>
</uif-list>
```

## Items with images:

``` html
<uif-list>
  <uif-list-item ng-repeat="message in vm.messages" uif-unread="{{message.isUnread}}" uif-unseen="{{message.isUnseen}}" uif-selected="{{message.isSelected}}" uif-type="itemWithImage">
    <uif-list-item-image><img ng-src="{{message.sender.photoUrl}}" alt="{{message.sender.name}}" /></uif-list-item-image>
    <uif-list-item-primary-text>{{message.sender.name}}</uif-list-item-primary-text>
    <uif-list-item-secondary-text>{{message.title}}</uif-list-item-secondary-text>
    <uif-list-item-tertiary-text>{{message.description}}</uif-list-item-tertiary-text>
    <uif-list-item-meta-text>{{message.time}}</uif-list-item-meta-text>
    <uif-list-item-actions>
      <uif-list-item-action ng-click="vm.mail(message)">
        <uif-icon uif-type="mail" />
      </uif-list-item-action>
      <uif-list-item-action ng-click="vm.delete(message)">
        <uif-icon uif-type="trash" />
      </uif-list-item-action>
      <uif-list-item-action ng-click="vm.delete(message)">
        <uif-icon uif-type="pinLeft" />
      </uif-list-item-action>
    </uif-list-item-actions>
  </uif-list-item>
</uif-list>
```

## Items with icons:

``` html
<uif-list>
  <uif-list-item ng-repeat="document in vm.documents" uif-unread="{{document.isUnread}}" uif-unseen="{{document.isUnseen}}" uif-selected="{{document.isSelected}}" uif-type="itemWithIcon">
    <uif-list-item-icon><img ng-src="{{document.iconUrl}}" alt="{{document.type}}" /></uif-list-item-icon>
    <uif-list-item-primary-text>{{document.title}}</uif-list-item-primary-text>
    <uif-list-item-secondary-text>{{document.name}}</uif-list-item-secondary-text>
    <uif-list-item-tertiary-text>{{document.summary}}</uif-list-item-tertiary-text>
    <uif-list-item-meta-text>{{document.modified}}</uif-list-item-meta-text>
    <uif-list-item-actions>
      <uif-list-item-action ng-click="vm.mail(document)">
        <uif-icon uif-type="mail" />
      </uif-list-item-action>
      <uif-list-item-action ng-click="vm.delete(document)">
        <uif-icon uif-type="trash" />
      </uif-list-item-action>
      <uif-list-item-action ng-click="vm.delete(document)">
        <uif-icon uif-type="pinLeft" />
      </uif-list-item-action>
    </uif-list-item-actions>
  </uif-list-item>
</uif-list>
```

All feedback welcome :smile:

**Comment by andrewconnell** [comment]
Damn I think @waldekmastykarz has set the standard for writing specs... No feedback from me. LGTM!

**Comment by waldekmastykarz** [comment]
:smile:

**Comment by waldekmastykarz** [comment]
I've started working on the List directive but unfortunately won't be able to pick it up for the next 2/3 weeks. My work so far is available in my fork on https://github.com/waldekmastykarz/ng-officeuifabric/tree/issue-24. Feel free to pick it up. Otherwise I'll pick it up in March the latest.

**Comment by andrewconnell** [comment]
All good... totally get it. Best of luck with work (_damn jobs!_) & hopefully (or not) it will still be here when you get back.

**Comment by andrewconnell** [comment]
FYI... fabric changed from `div` to `li` for better markup - https://github.com/OfficeDev/Office-UI-Fabric/pull/331

**Comment by waldekmastykarz** [comment]
:+1:

**Comment by waldekmastykarz** [comment]
Feature is code complete. Next step finalizing tests and documentation.

**Comment by waldekmastykarz** [comment]
It's taking a little longer than anticipated: while building tests I've noticed that the code coverage was pretty low. So to refactor them I changed the logic of how selected items how being dealt with so that we can avoid similar problems that we have with tables. If all is well the directive should be finished soon and we can use the lessons learned to refactor table.

**Comment by waldekmastykarz** [comment]
Tests with 100% code coverage are now done and pushed to my feature branch. Last step: code docs and samples.
