### ISSUE TITLE
TextField can't be disabled or set to be required

### ISSUE THREAD

**Issue by andikrueger** [ngOfficeUIFabric/ng-officeuifabric#240]
The uif-textfield directive can't be disabled or set to be required. For example: uif-label directive supports both HTML attributes #22 

It would be great to have these attributes consistent within all form elements.

**Comment by rolandoldengarm** [comment]
We implement exactly what is in the [component examples](http://dev.office.com/fabric/components/textfield). Disabled and required are not options. 

But I agree that disabled should be added.
Not sure what to do with required. What are you trying to achieve? You can use Angular form validation already? Not sure what the added class would deliver.

**Comment by ghost** [comment]
My initial response was that the Office UI Fabric component does not have required and/or disabled, and we are copying what they do.
Then I remember that we initially had this, and that it's also working from a CSS point of view. Check out the "old" example site: http://officeuifabric.com/components/text-field/

So, I've implemented it. PR: https://github.com/ngOfficeUIFabric/ng-officeuifabric/pull/241
