### ISSUE TITLE
Demo breadcrumb missing CSS

### ISSUE THREAD

**Issue by Elfayer** [ngOfficeUIFabric/ng-officeuifabric#242]
In the demo website, you provide a breadcrumb demo that has a really basic style, I guess it is not the correct behavior. Here is a picture of the result you're showing:

![image](https://cloud.githubusercontent.com/assets/15869149/13946335/34b9aa3a-f014-11e5-934c-ed2c26e4036a.png)

Link: http://ngofficeuifabric.com/demos/uifBreadcrumb/

**Comment by andrewconnell** [comment]
Issue with the fabric 2.1.0 release where the breadcrumb styles are missing from the Fabric distribution. This is fixed in 2.2.0 so when we ensure our directives are not affected by updating the fabric version & use 2.2.0, this issue will get fixed automatically. Therefore we won't fix it now.

**Comment by andrewconnell** [comment]
Also an issue with how we are rendering this component as Fabric changed their rendering. See #260.

**Comment by andrewconnell** [comment]
Closing the loop on this... the challenge was that Fabric changed the implementation of breadcrumb & their CSS which caused issues with our rendering (ref #260). This has been fixed in PR #261

**Comment by andrewconnell** [comment]
The demo will get updated in the next release.
