### ISSUE TITLE
<uif-choicefield-group> not supporting 'ng-change'

### ISSUE THREAD

**Issue by Elfayer** [ngOfficeUIFabric/ng-officeuifabric#243]
@rolandoldengarm

I guess it is not the only element not allowing this behavior, but in my case I have a list of radio buttons (`<uif-choicefield-option>`) that are grouped inside `<uif-choicefield-group>` and I can't use `ng-change` that is supported by Angular natively: https://docs.angularjs.org/api/ng/input/input%5Bradio%5D

```
<uif-choicefield-group ng-model="selectedValue" ng-change="update()"> <!-- This will do nothing -->
    <uif-choicefield-option uif-type="radio" value="value1">Text 1</uif-choicefield-option>
    <uif-choicefield-option uif-type="radio" value="value2">Text 2</uif-choicefield-option>
    <uif-choicefield-option uif-type="radio" value="value3">Text 3</uif-choicefield-option>
    <uif-choicefield-option uif-type="radio" value="value4">Text 4</uif-choicefield-option>
</uif-choicefield-group>
```
### Expected Behavior

`ng-change` directive should be evaluated.
### Actual Behavior

`ng-change` is not taken in account.

**Comment by Elfayer** [comment]
A solution to this was to use a watcher (`$scope.$watch()`) to call `update()` on `selectedValue` change.

**Comment by ghost** [comment]
Do you by any chance have multiple uif-choicefield-group's on a page?
I've found out that it works fine in a test case, but not in the demo. However, if I comment out all uif-choicefield-group except one, it works. See https://github.com/ngOfficeUIFabric/ng-officeuifabric/pull/252 for the test case.

I've raised a bug for the multiple uif-choicefield-group issue: https://github.com/ngOfficeUIFabric/ng-officeuifabric/issues/251

**Comment by Elfayer** [comment]
It's good you found a correction. Although I think my issue comes from another test case. I created a JSFiddle : https://jsfiddle.net/1zudpb3w/1/

I believe the issue I was describing is exactly the issue : #245 
Since the field wasn't emptied, I thought it wasn't called.

### Steps to Reproduce Behavior
- Select a Type
- Select an AddressBook
- Select a Category
- Change the Type

=> The field Category isn't empty.

**Comment by ghost** [comment]
I think we agree that ng-change is being called; I've added an alert to show that: https://jsfiddle.net/yzr9hos8/

The issue is that setting ng-model of uif-dropdown was not working, see https://github.com/ngOfficeUIFabric/ng-officeuifabric/issues/245

Please test with the latest dev version; it should be working there. Otherwise please raise another issue.
