### ISSUE TITLE
Remove "Pick one" from <uif-choicefield-group>

### ISSUE THREAD

**Issue by Elfayer** [ngOfficeUIFabric/ng-officeuifabric#244]
When using `<uif-choicefield-group>` with radio buttons, there is a text added on top of the radios : "Pick one". This is not good for internationalization. Is it possible to remove it in a way ?

See in demo page : http://ngofficeuifabric.com/demos/uifChoicefield/

**Comment by ghost** [comment]
Valid issue. Requires another directive "uif-choicefield-group-title" to be able to wrap arbitrary content. I feel we should default to an empty string, but this may be seen as a breaking change as right now the default text is "Pick one". @ngOfficeUIFabric/ngofficeuifabric-members  ?

**Comment by s-KaiNet** [comment]
I'd rather completely remove "Pick one" and give a user option to use any markup he wants right before choice field group.
