### ISSUE TITLE
<uif-dropdown> When 'ng-model' value is 'null', the value shown is the last selected, while it should be empty.

### ISSUE THREAD

**Issue by Elfayer** [ngOfficeUIFabric/ng-officeuifabric#245]
### Steps to Reproduce Behavior

Let's take the demo example : 

```
<uif-dropdown ng-model="dropdownValue" >
    <uif-dropdown-option value="value1">Value 1</uif-dropdown-option>
    <uif-dropdown-option value="value2">Value 2</uif-dropdown-option>
    <uif-dropdown-option value="value3">Value 3</uif-dropdown-option>
    <uif-dropdown-option value="value4">Value 4</uif-dropdown-option>
</uif-dropdown>
```

If I click on "Value 1", the dropdown will show the label "Value 1". Now if in my Controller I set the value of "dropdownValue" (`ng-model` variable) to `null`, it still shows the "Value 1" label, while it should show an empty field.
### Expected Behavior

If `ng-model` variable is `null`, label should be empty.
### Actual Behavior

If `ng-model` variable is `null`, label shows last label shown.

**Comment by ghost** [comment]
Valid issue.
It's more generic though. The issue is that NULL is not one of the values. So the actual issue is: when setting the scope value to an unknown value, the displayed title should be empty.
E.g. if you would set it to "value5", it should be empty as well.

**Comment by oviava** [comment]
Require similar behaviour
