### ISSUE TITLE
<uif-nav-bar> Not showing interpolation in uif-text attribute

### ISSUE THREAD

**Issue by Elfayer** [ngOfficeUIFabric/ng-officeuifabric#246]
For internationalization, I use a pipe filter as follow : `{{'people_title' | localization}}`, `people_title` is a key in a JSON `localization` filter has loaded.

Anyway, I need to put an angular template in the navbar because depending on the language, it is not the same text. And the following code doesn't work : 

`<uif-nav-bar-item uif-text="{{nav[0]}}"></uif-nav-bar-item>`
### Expected Behavior

`uif-text` should allow interpolation.
### Actual Behavior

`uif-text` doesn't support interpolation.
### Steps to Reproduce Behavior

Here is a JSFiddle you can play with : https://jsfiddle.net/gdfh92zd/5/

**Comment by s-KaiNet** [comment]
`uif-text` accepts a reference from scope and not a string. So in your example you should use following approach: 
[https://jsfiddle.net/gj8kxg57/2/](https://jsfiddle.net/gj8kxg57/2/)  
For advanced scenarios you can always use `<uif-content>` like in the fiddle above (last item).

**Comment by Elfayer** [comment]
Thanks for your answer :)

`<uif-content>` saved me because my data is loaded asynchronously.

I updated your JSFiddle to show a working example with asynchronous data: https://jsfiddle.net/gj8kxg57/4/

**Comment by s-KaiNet** [comment]
So I'm closing this one.
