### ISSUE TITLE
<uif-nav-bar> Not supporting page navigation

### ISSUE THREAD

**Issue by Elfayer** [ngOfficeUIFabric/ng-officeuifabric#247]
I'd like to use the `<uif-nav-bar>` (http://ngofficeuifabric.com/demos/uifNavbar/) component to manage my navigation and follow my routing. This implies that :
### Expected Behavior
- When I click on a tab, it stays selected until I change the page.
- When a tab is disabled, there is a visible style that shows it is not available (grey text color and/or italic ?), cursor is set to `default` and there is no visual effect when we click on it. (although I could override this)

I suggest to add the possibility to keep the navbar state with a variable, as it is done on Angular Material with `md-selected="selectedIndex"` (https://material.angularjs.org/latest/api/directive/mdTabs)
### Actual Behavior
- When I click on a tab and click away, the tab is deselected.
- When a tab is disabled, there is no visible style that say it is, cursor is still set to `pointer` (though there is no `border-bottom`, it is still confusing) and there is a visual effect on click.

**Comment by s-KaiNet** [comment]
To summarize your points (in reverse order):  
1. Track selected index
2. Styles for disabled item are not correct
3. Selection state when you click somewhere  

For `#1` I agreed and that can be good addition. 
For `#2` - cursor should be default - this is a bug in our library. Other styling - grey color and may be visual effect when clicking - I believe that's [Office-UI-Fabric](https://github.com/OfficeDev/Office-UI-Fabric) bug. Can you please raise an issue in their repository? 

`#3` the most intricate.  We can add additional option to directive controlling if we need to deselect item by clicking on it. Should we do that or not? It adds complexity and nav bar becomes more like tabs. What about if nav bar item holds contextual menu? Should we close it or not?  
Looking for other opinions @ngOfficeUIFabric/ngofficeuifabric-members

**Comment by Elfayer** [comment]
I have been looking the Office UI Fabric Components, and I'm wondering if what I'm looking for is not the Pivot ?

cf: http://dev.office.com/fabric/components/pivot

**Comment by s-KaiNet** [comment]
Yep, may be the pivot is better rather than nav bar according to your needs. Consider it.

**Comment by s-KaiNet** [comment]
In that case I'm wondering do we really need track selected index for nav bar?

**Comment by Elfayer** [comment]
I think you're right, I should go for the pivot. The thing is that there is no pivot currently.
Nor in the demos: http://ngofficeuifabric.com/demos/
nor in the library: https://github.com/ngOfficeUIFabric/ng-officeuifabric/tree/master/src/components

**Comment by jjczopek** [comment]
Pivot component is under construction. I have came up with specification here: #33. From the demos that come from Fabric website, it looks like this actually could solve your issue. Pivot is supposed to maintain information about selected item.

**Comment by Elfayer** [comment]
Do you know when it is supposed to be supported ?

**Comment by jjczopek** [comment]
I started working on it, but have limited time currently. I think I should be able to raise PR late next week.

**Comment by andrewconnell** [comment]
Any action items from this? The discussion looks finished so can we close this?

**Comment by s-KaiNet** [comment]
I think so. Issue #249  created.
