### ISSUE TITLE
Nothing is rendered after a <uif-textfield>.

### ISSUE THREAD

**Issue by Elfayer** [ngOfficeUIFabric/ng-officeuifabric#248]
When a `<uif-textfield>` is on a view, what is written after it isn't rendered (not even visible in the HTML file received)

Here is a JSFiddle that show the issue:
https://jsfiddle.net/gj8kxg57/6/

**Comment by ghost** [comment]
Don't use self-closing tags with custom Angular directives.
This works: https://jsfiddle.net/1zudpb3w/

**Comment by Elfayer** [comment]
Thanks =)

Just to notice that I used the synthax of the documentation : http://ngofficeuifabric.com/demos/uifTextfield/

**Comment by s-KaiNet** [comment]
Yep, that's an issue when you need to update demo in two places - your actual code which is running and markup showing this code. Sometimes you forget to update markup.  
To solve this I created simple directive named `raw` and using it in my demos. Consider `components\contextualmenu\demo\index.html`  
For example to demonstrate multi selection menu, you need only two directives (both using the same source): 

`<ng-include src="'multiSelection.html'"></ng-include>` and `<raw src="'multiSelection.html'"></raw>`  
With this approach you need to update code only in one place.  
I'm proposing for everybody to use this approach @ngOfficeUIFabric/ngofficeuifabric-members
