### ISSUE TITLE
Component to create: listitem

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#25]
Official link to component description & demo: http://dev.office.com/fabric/components/listitem

_Screenshot of web analytics for the original http://officeuifabric.com site by @andrewconnell. Use this to see what are the most popular components: http://imgur.com/gallery/buUcyQv_

**Comment by waldekmastykarz** [comment]
As mentioned in #24: since a list item doesn't exist outside of a list how about we combine #25 with #24 and provide a single component that consists of list and list item?

**Comment by andrewconnell** [comment]
Sounds good... closing this one to "merge" with #24.
