### ISSUE TITLE
<uif-choicefield-group> Can't use multiple directives on a page.

### ISSUE THREAD

**Issue by ghost** [ngOfficeUIFabric/ng-officeuifabric#251]
When using multiple uif-choicefield-group elements on a page, the ng-model used seems to be the first one. E.g. 

```
<uif-choicefield-group ng-model="val1">...</uif-choicefield-group>
<uif-choicefield-group ng-model="val2">...</uif-choicefield-group>
```

When clicking on option in the second, val1 is updated, and not val2.

**Comment by jjczopek** [comment]
@rolandoldengarm: does this still apply? I have setup a codepen and I'm unable to reproduce:
http://codepen.io/jjczopek/pen/rLNGXR

**Comment by ghost** [comment]
Just checking again @jjczopek and indeed does not seem to apply anymore. Closed.
