### ISSUE TITLE
<uif-dropdown> Not loading default value

### ISSUE THREAD

**Issue by Elfayer** [ngOfficeUIFabric/ng-officeuifabric#253]
I have a `<uif-dropdown>` that should show the default `ng-model` value set on the controller, but it doesn't. See : https://jsfiddle.net/u223Ljj9/3/

The problem definitely comes at load time, afterwards the `ng-model` value linking is working properly (see using the button)
### Expected Behavior

The dropdown shows the value set from Controller.
### Actual Behavior

The dropdown is empty while a value is set by default in the Controller

**Comment by ghost** [comment]
Duplicate: https://github.com/ngOfficeUIFabric/ng-officeuifabric/issues/230
