### ISSUE TITLE
<uif-dropdown> change to selectedTitle on resetting ng-model

### ISSUE THREAD

**Issue by oviava** [ngOfficeUIFabric/ng-officeuifabric#256]
``` html
<uif-dropdown ng-model="bindValue" selected-title="Select Element">
   <uif-dropdown-option ng-repeat="elem in elements" value="{{elem.value}}">{{elem.label}}</uif-dropdown-option>
<uif-dropdown>
```

on resetting bindValue to "" reset to selectedTitle

**Comment by oviava** [comment]
Apologies, closing for duplicate https://github.com/ngOfficeUIFabric/ng-officeuifabric/issues/245

**Comment by oviava** [comment]
think this might still be an issue:

``` javascript
if (!found) {
                    // no option found
                    self.$scope.selectedTitle = '';
                }
```

If no option shouldn't it be set to the passed selectedTitle ?!

**Comment by oviava** [comment]
correction, after checking the code a bit. Would like to be able to set a placeholder for the dropdown directive. I assumed selectedTitle was used like that, but apparently that's not an option. at the moment uif-dropdown doesn't support any sort of placeholder though it would be easy to do that via selectedTitle

**Comment by oviava** [comment]
one option would be to set the selectedTitle in the preLink function

``` javascript
scope.selectedTitle = instanceElement.attr('selected-title');
```

and then, if ng-model is null / undefined set it to the attribute set selected-title

**Comment by andrewconnell** [comment]
Can you please explain this a bit more. I don't understand the issue... is this a bug, enhancement, change... ?

When creating an issue & PR, a template is used that explains what you need to include... please follow the guidelines in the template to help us understand what's going on.

**Comment by oviava** [comment]
Hi Andrew, apologies, I may have done this in a bit of a rush.

Similar to search box, it would be nice to have something like a placeholder for dropdown components. I've done a pull request, this works for me at the moment, passed all the tests but not sure if it goes with the direction/pattern you see ngOfficeUIFabric.

See https://github.com/ngOfficeUIFabric/ng-officeuifabric/pull/332

**Comment by andrewconnell** [comment]
Thanks for the update... but you've just changed the directive. I don't see any updates to demos or tests to document the usage and showing an example as well as adding coverage to prove your changes work. I'm going to close the PR for now because it isn't ready for merging, but please feel free to resubmit in the future once these things are addressed.

**Comment by oviava** [comment]
Fair enough, will try to allocate some time for a proper PR.

**Comment by ghost** [comment]
There is already a solution to do this, just add an uif-dropdown-option with empty value. I don't see the need for another attribute to be honest.
