### ISSUE TITLE
<uif-choicefield-option> do not support ng-disabled

### ISSUE THREAD

**Issue by Elfayer** [ngOfficeUIFabric/ng-officeuifabric#257]
I'd like to be able to use `ng-disabled` on `<uif-choicefield-option>`. Otherwise I could use `disabled="{{myVar}}"`, but it is not dynamically bound to the controller.
### Expected Behavior

`ng-disabled` is supported => I can update a value from the controller that updates the `disabled`attribute from the view.
### Actual Behavior

`ng-disabled` is not supported.
### Steps to Reproduce Behavior

https://jsfiddle.net/txryc7b8/1/

**Comment by andrewconnell** [comment]
Wouldn't this apply to _all_ directives, not just the one you mention in this issue?

My understanding is most (all maybe?) directives already support `disabled`... what does `ng-disabled` give you that `disabled` doesn't?

**Comment by ghost** [comment]
This is an issue; disabled doesn't work either. It stays disabled, no matter what the value is for isDisabled. Similar to this one:

https://github.com/ngOfficeUIFabric/ng-officeuifabric/issues/259

I think this applies to more directives.

**Comment by andrewconnell** [comment]
I fear you are right @rolandoldengarm… we need to go look at every directive and see if this is an issue, ensuring we have a test to cover this scenario. I’ll take this on.
