### ISSUE TITLE
<uif-dropdown> Element disabled for any value of disabled, true or false

### ISSUE THREAD

**Issue by oviava** [ngOfficeUIFabric/ng-officeuifabric#259]
``` html
<uif-dropdown ng-model="selectedElement" selected-title="Select Element" disabled={{false}}>
```

Expected behaviour - element should be enabled

Actual behaviour - element is disabled

I'm trying to dynamically control the status of the element but if the attribute disabled exists on the element it will always be disabled, regardless of value.

**Comment by andrewconnell** [comment]
Hmmm... @rolandoldengarm is this related to the other fixes you recently implemented for other directives? Is this something that affects all our directives?

**Comment by rolandoldengarm** [comment]
In HTML, disabled is not a true/false attribute. If it's there, it's disabled.

Not tested, but I think ng-disabled should work @oviava ?

**Comment by ghost** [comment]
No it's not related to the recent changes.
Disabled is not a true/false attribute by default in HTML.
Ng-disabled should do the trick, it adds /removes the disabled attribute based on the expression. For some reason that does not work.

https://jsfiddle.net/pvujzamh/

**Comment by oviava** [comment]
> actually https://www.w3.org/TR/html5/forms.html#enabling-and-disabling-form-controls:-the-disabled-attribute
> 
> `The disabled content attribute is a boolean attribute.`

edit: ignore above, incorrect, left comment for posterity

and no, ng-disabled doesn't work either

**Comment by oviava** [comment]
actually .. I'll eat my own words :). still, would be nice to able to control disabled or not dynamically, there is really no point on setting disabled on an element without being able to dynamically change it

**Comment by ghost** [comment]
It's a valid bug. Ready for dev.
