### ISSUE TITLE
Component to create: navbar

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#26]
Official link to component description & demo: http://dev.office.com/fabric/components/navbar

_Screenshot of web analytics for the original http://officeuifabric.com site by @andrewconnell. Use this to see what are the most popular components: http://imgur.com/gallery/buUcyQv_

**Comment by s-KaiNet** [comment]
### `NavBar` Specs:

``` html
<uif-nav-bar uif-overlay="light|dark">
  <uif-nav-bar-item uif-type="menu|search|link" uif-click="onMenuItemClick" 
                    uif-position="right|left" uif-text="myLink" uif-is-disabled="isDisabled">
      <uif-text><b>My Menu item</b></uif-text>
 </uif-nav-bar-item>
</uif-nav-bar>
```

`<uif-nav-bar>` - root element:  
- `@uifOverlay` - optional, string `light` or `dark`. Validation should be included.  

`<uif-nav-bar-item>` - represents nav bar item:
- `@uifType` - optional, default is `link`. `search` renders search box, `menu` renders sub-menu, `menu` assumes `<uif-contextual-menu>` will be presented as child. Validation should be included.  
- `&uifClick` - optional, click handler. For `search` item triggered by clicking on search icon or keyboard `enter` event inside search box.  
- `@uifPosition` - optional, default `left`.  Validation should be included.  
- `=uifText` - label for the nav bar item. Can be attribute or separate directive (see below)
- `=uifIsDisabled` - optional boolean, set menu item to disabled state  

`<uif-text>` - directive for nav bar item label (allowing advanced control over label markup). 

### Sample:

``` html
<uif-nav-bar uif-overlay="dark">
 <uif-nav-bar-item uif-type="search" uif-click="onSearch"></uif-nav-bar-item>
 <uif-nav-bar-item uif-click="onHomeClick">
   <uif-text>Home</uif-text>
 </uif-nav-bar-item>
 <uif-nav-bar-item uif-text="myLink"></uif-nav-bar-item>
 <uif-nav-bar-item uif-type="menu">
  <uif-text>More</uif-text>
  <uif-contextual-menu> ....</uif-contextual-menu>  
 </uif-nav-bar-item>
 <uif-nav-bar-item uif-text="'Upload'" uif-position="right"></uif-nav-bar-item>
</uif-nav-bar>
```

Additional points to consider\discussion:
- Overlay is an attribute and will be translated to existing directive `uif-overlay` 
- Search component is not an individual directive, but just regular `uif-nav-bar-item`. From my point this helps to have cleaner markup. It has completely different markup than SearchBox and it will be hard to incorporate SearchBox into the NavBar
- Currently Office UI Fabric supports only one level menu. Contextual menu supports multi leveling, but we may have a problem with styles on smaller devices (if view port smaller than 480px nav bar collapsed to single icon). 
- `uif-text` - new directive, name can be other, I'm going to reuse that on contextual menu as well  

### Latest Spec based on conversation and implemented:

``` html
<uif-nav-bar uif-overlay="light|dark">
  <uif-nav-bar-search placeholder="Search for smth" uif-on-search="onSearchCallback()">
  </uif-nav-bar-search>
  <uif-nav-bar-item uif-type="menu|link" uif-position="right|left" uif-text="myLink" 
                   disabled="isDisabled">
      <uif-nav-bar-content><b>My Menu item</b></uif-nav-bar-content>
 </uif-nav-bar-item>
</uif-nav-bar>
```

**Comment by jjczopek** [comment]
I think it would be good to change `uif-is-disabled="isDisabled"` to `disabled="isDisabled"`. 
`disabled` is a well known attribute and clearly indicated the purpose. I did the same for label - #22.

Other than that, LGTM.

**Comment by andrewconnell** [comment]
For the `uif-text`, can you look at how the design for the commandbar #17 uses something like `uif-*-content`? For instance, what if someone wanted to include an icon, image or more than just text.

Also :+1: to @jjczopek suggestion above for `disabled`

**Comment by s-KaiNet** [comment]
Thank you for your responses.  
I'm renaming `uif-text` to `uif-nav-bar-content`, change `uif-is-disabled` to simply `disabled`.  
Updated spec:  

``` html
<uif-nav-bar uif-overlay="light|dark">
  <uif-nav-bar-item uif-type="menu|search|link" uif-click="onMenuItemClick" 
                    uif-position="right|left" uif-text="myLink" disabled="disabled">
      <uif-nav-bar-content><b>My Menu item</b></uif-nav-bar-content>
 </uif-nav-bar-item>
</uif-nav-bar>
```

**Comment by s-KaiNet** [comment]
During development I'm shifting to have separate nav bar search directive instead of relying on menu type.  
Reasons:  
- that might be useful to provide `placeholder` for search input, I can add `uif-placeholder` to `uif-nav-bar-item`, but this attribute is intended for search only, semantically that's not correct
- `uif-click` also not very good name for search event, it's better `uif-on-search`, with custom directive for search nav bar item this can be done
- there is a chance that additional changes might be necessary for search part. From Office UI Fabric Team or from community (for example generate search event as you type to provide some kind of auto completion etc..). If we have separate directive for nav bar search, changes will be implemented faster. 

So updates specs:   

``` html
<uif-nav-bar uif-overlay="light|dark">
  <uif-nav-bar-search placeholder="Search for smth" uif-on-search="onSearchCallback()"></uif-nav-bar-search>
  <uif-nav-bar-item uif-type="menu|link" uif-click="onMenuItemClick" 
                    uif-position="right|left" uif-text="myLink" disabled="disabled">
      <uif-nav-bar-content><b>My Menu item</b></uif-nav-bar-content>
 </uif-nav-bar-item>
</uif-nav-bar>
```

**Comment by andrewconnell** [comment]
Sounds good... but why a custom attribute `uif-click` for the `uif-nav-bar-item` (_I should have asked this above_)? Could standard events not be used instead of this or use the angular ones like `ngClick`?

My concern is that if this is done, what about the next logical questions:
- what about creating a hover event?
- what about creating a mouse down event?
- what about creating a mouse over event?

The directive would have to implement all of these events. Trying to make it so we create less.

The `uif-on-search` makes sense as it's a custom event you do want to fire and let the developer dictate what happens in that case.

**Comment by ghost** [comment]
For #17, I opted to not implement click and hover events for the same reason - leave it with the user as they may want all manner of things to happen on click/hover etc.

**Comment by s-KaiNet** [comment]
Good points, agreed, thank you. That's even easier - I'll remove custom attribute for click and give a user chance to decide which kind of events he wants.  
Taking this into account contextual menu directive also needs this change.
