### ISSUE TITLE
<uif-table> selection doesn't work

### ISSUE THREAD

**Issue by emiliogg84** [ngOfficeUIFabric/ng-officeuifabric#262]
Selection not work!

**Comment by andrewconnell** [comment]
This kind of an issue does not help. The demo for he `uif-table` shows the selection of a row working: http://ngofficeuifabric.com/demos/uifTable/

If you have a specific issue you can repo to help us understand what you mean when you say it doesn't work, that would help. But as this issue stands, it's not helpful or actionable.
