### ISSUE TITLE
Ensure all directives have test case to verify disabled & ng-disabled work

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#268]
Uncovered in #257, we need to look at each directive and ensure it has a test case to confirm `disabled` and `ng-disabled` perform as expected and if they don't create issues to fix each one.

**Comment by ghost** [comment]
Most directives I've checked only check for disabled once in the link.
To fix this, the directive has to watch for the attribute. 

I've fixed it in dropdown + added demo + test case: https://github.com/ngOfficeUIFabric/ng-officeuifabric/pull/271

**Comment by andrewconnell** [comment]
The following directives that are checked off have either been fixed & confirmed this isn't something to address with them. If they are unchecked, that means investigation is still required.
- [x] `uif-breadcrumb` (n/a)
- [x] `uif-button` (fixed in 59a2b87)
- [x] `uif-callout` (n/a)
- [x] `uif-choicefield` (fixed in 1881150)
- [x] `uif-commandbar` (n/a)
- [x] `uif-content` (n/a)
- [x] `uif-contextualmenu` (n/a)
- [x] `uif-datepicker`
- [x] `uif-dialog` (n/a)
- [x] `uif-dropdown` (fixed in 6d71569)
- [x] `uif-icon` (n/a)
- [x] `uif-label` (n/a)
- [x] `uif-link` (n/a)
- [x] `uif-list` (n/a)
- [x] `uif-navbar` (n/a)
- [x] `uif-orgchart` (n/a)
- [x] `uif-overlay` (n/a)
- [x] `uif-panel` (n/a)
- [x] `uif-persona` (n/a)
- [x] `uif-personacard` (n/a)
- [x] `uif-progressindicator` (n/a)
- [x] `uif-searchbox`
- [x] `uif-spinner` (n/a)
- [x] `uif-table` (n/a)
- [x] `uif-textfield` (fixed in 1e30042)
- [x] `uif-toggle` (fixed in 86675be)

**Comment by jjczopek** [comment]
I think it's not required for persona card.

**Comment by waldekmastykarz** [comment]
The list is similar to table and a disabled state could apply either to selecting list items or executing actions on them. Should any of these be covered by the disabled state?

**Comment by andrewconnell** [comment]
@waldekmastykarz From my POV, tables aren't normally seen as input controls so the fact we over the ability to select items, I don't think `disabled` makes sense because the table already has a toggle if rows can be selected, right?

As for the list, that's usually seen as a replacement for the `<select>` input control or a classic dropdownlist so that one should have the ability to be disabled. Individual items within the list don't need to handle disabled / not.

**Comment by waldekmastykarz** [comment]
@andrewconnell table: agreed.

list: just like the table you can disable selecting items on the list. So the only thing a disabled state could influence are the actions on list items.

**Comment by andrewconnell** [comment]
Hmmm… but for the list control, would it not make more sense to the developer to look for the disabled | ng-disabled state considering it’s typically an input control? If the fabric list component has a disabled CSS class, then it would imply that you can disable it and change the look & feel of it to a disabled control.

Thoughts?

**Comment by waldekmastykarz** [comment]
I've just checked Fabric v2.3 CSS and there is no sign of disabled state for the List, List Item or List Item Action. With that could we assume that the List was not intended to be disabled and there is nothing we need to do about it?

**Comment by s-KaiNet** [comment]
PR pushed for contextual menu, navbar fixed via contextual menu, because nav bar elements are contextual menus.

**Comment by tom2all** [comment]
I think support for "ng-disabled" is broken (at least for "uif-button"). ng-disabled attribute should take an expression as value (see https://code.angularjs.org/1.5.5/docs/api/ng/directive/ngDisabled).

My template:
`<button type="submit" uif-type="primary" ng-disabled="vc.isButtonDisabled()">Button</button>`
is rendered to:
`<button type="submit" uif-type="primary" class="ms-Button ms-Button--primary ng-isolate-scope" ng-class="{'is-disabled': disabled}" ng-disabled="vc.isButtonDisabled() disabled">[...]`

Since "`vc.isButtonDisabled() disabled`" is not a valid angular expression, this generates an angular syntax error.
Additionally, I don't think you need to add "`ng-class="{'is-disabled': disabled}"`" when parsing "ng-disabled", because angular does this anyway.
The error appears with "uif-button" when upgrading from 0.8.3 to 0.8.4. I'm using angular 1.5.5.

**Comment by s-KaiNet** [comment]
@tom2all that's definitely the bug. Tests are passing only because coincidentally the property controlling disabled called `"disabled"` :)  
#319

**Comment by tom2all** [comment]
@s-KaiNet , @andrewconnell : Thank you for fixing this bug and releasing the fix so fast!
I've upgraded my app to 0.10.0 and all my buttons work fine again! :+1:

**Comment by jjczopek** [comment]
Added support for disabled & ng-disabled to uif-datepicker (commit 13869961158790f654a1cbb45d30591a6a7c31ab).

**Comment by jjczopek** [comment]
Added support for disabled & ng-disabled to `uif-searchbox` (276ff6789a1ab1b977c39705d6297e286c0fc106)

**Comment by jjczopek** [comment]
Regarding orgchart - after looking into Fabric CSS, I haven't found any disabled classes for orgchart. I therefore I suggest that this exercise is not applicable to uif-orgchart component.
