### ISSUE TITLE
Implementation of Office App Launcher

### ISSUE THREAD

**Issue by ruisilva450** [ngOfficeUIFabric/ng-officeuifabric#269]
Create the necessary angular directives and implementation to get the same Office App Launcher as the image.

![alt text](https://msdn.microsoft.com/office/office365/HowTo/images/Office365_AppLauncher_Launcher.png)

**Comment by andrewconnell** [comment]
Personally I'd love to see this, but it won't be part of our first milestone as we want full parity with Fabric first. At the moment this is on their [roadmap](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/ROADMAP.md)... suggest you push on their issue https://github.com/OfficeDev/Office-UI-Fabric/issues/81 to get them to do it.

We are not trying to create new things just yet, rather we're trying to create Angular Directives for fabric UI components.
