### ISSUE TITLE
Component to create: overlay

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#28]
Official link to component description & demo: http://dev.office.com/fabric/components/overlay

_Screenshot of web analytics for the original http://officeuifabric.com site by @andrewconnell. Use this to see what are the most popular components: http://imgur.com/gallery/buUcyQv_

**Comment by johnmeilleur** [comment]
I will take this one on.

**Comment by johnmeilleur** [comment]
**SPEC**

This one should be simple and I guess it is intended to be incorporated with other components (e.g. dialog)

main component directive: `<uif-overlay></uif-overlay>`
optional boolean attribute uif-overlay-dark.  Defaults to false and when true adds the --dark class to the overlay.

examples:
`<uif-overlay> Hello World </uif-overlay>`
`<uif-overlay uif-overlay-dark="true"> Hello World </uif-overlay>`
`<uif-overlay> <uif-dialog>...</uif-dialog> </uif-overlay>`

**Comment by andrewconnell** [comment]
IMHO I think this would make more sense:

`<uif-overlay uif-mode="[light | dark]">Hello World</uif-overlay>`

No need to include the name **overlay** in the attribute name as it's not going to be a directive. Also, one of the modes would be the default if omitted.

**Comment by johnmeilleur** [comment]
I think that makes sense as well.  I've submitted a pull request to review.

**Comment by andrewconnell** [comment]
Since you're looking at an enum, the next merge of PR's to `dev` will introduce two new directive guidelines which will affect this directive. Specifically check [guideline 007](https://github.com/andrewconnell/ng-officeuifabric/blob/doc-guidelineupdate/docs/guides/DIRECTIVE-CHECKLIST.md#directive-attribute-validation)... it's in PR #94... guideline 008 is also related.

To be clear, theses aren't guidelines today, but we will be creating issues & assigning to the original directive authors in the coming days on stuff to address. So... when I review all the PRs in the next few days, if you don't have this no worries... we'll just create an issue and assign it to you, but if you want to be proactive, mentioning it now.

**Comment by johnmeilleur** [comment]
Thanks.  I'll review and update accordingly.

**Comment by waldekmastykarz** [comment]
:+1: on the spec @andrewconnell suggested

**Comment by johnmeilleur** [comment]
I've submitted the PR to follow the guideline for attribute validation and error messages.  I took a slightly different approach to injecting the logService.  Not sure if one method is better then another.

@andrewconnell can you change the label of this issue to work in progress?

**Comment by johnmeilleur** [comment]
Ready for review PR #103
