### ISSUE TITLE
<uif-dropdown>: uif-label is not rendered

### ISSUE THREAD

**Issue by andikrueger** [ngOfficeUIFabric/ng-officeuifabric#281]
### Expected Behavior

uif-label is rendered
Compare to: http://dev.office.com/fabric/components/dropdown
### Actual Behavior

uif-label is not rendered

**Comment by andrewconnell** [comment]
Labels are not automatically added to components, this is up to the developer to add a label using our `uif-label` directive.

**Comment by andikrueger** [comment]
Thank you for the fast response. Other components like uif-textfield do offer contain the uif-label. it would be great to have these consistent between typical form components.

**Comment by andrewconnell** [comment]
Thanks for bringing this up... we'll make sure to standardize across all directives.
