### ISSUE TITLE
Triage directives that don't respect ng-disabled

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#282]
Not all of our directives respect the `ng-disabled` directive. We need to look at each one and identify which ones need to get updated.

**Comment by ghost** [comment]
Isn't this a duplicate of https://github.com/ngOfficeUIFabric/ng-officeuifabric/issues/268 ?

**Comment by andrewconnell** [comment]
Yup... my bad...
