### ISSUE TITLE
Toggle Component should expose other arguments

### ISSUE THREAD

**Issue by sjclemmy** [ngOfficeUIFabric/ng-officeuifabric#289]
Hi,
I'm using the toggle component and I want to be able to do some other actions when the user clicks.
I'd normally achieve this by adding an expression to ng-change. E.g. `ng-change="doSomeStuff(withMe)"`. 

I've put `ng-click="doSomeStuff(withMe)"`, but the click fires twice so isn't ideal.

I'd suggest a change to expose this as an option. Also, might as well add the other arguments `ng-true-value="expression", ng-false-value="expression"`.

This would result in being able to do something like this:

 `<uif-toggle uif-label-off="Don't Upload" uif-label-on="Upload" ng-model="myModel" ng-change="doSomeOtherStuffWith(myModel)"/>`

Is this a good idea or is there another way of achieving this that I am missing?

I'm happy to do the change and submit a PR.

**Comment by andrewconnell** [comment]
Hey @rolandoldengarm as the original author, you want to throw your thoughts here?

**Comment by sjclemmy** [comment]
I had a bit of a play around with how this might work and I implemented something like this (without using ngOfficeUIFabric, but it would be much cleaner if it was integral to the component):

```
<div ng-class="toggleClass" class="ms-Toggle"><span class="ms-Toggle-description"></span><input
                        type="checkbox" id="{{::$id}}"
                        class="ms-Toggle-input"
                        ng-change="vm.onToggle()" ng-model="toggleState"><label
                        for="{{::$id}}" class="ms-Toggle-field"><span
                        class="ms-Label ms-Label--off ng-binding">Don't Use</span><span
                        class="ms-Label ms-Label--on ng-binding">Use</span></label>
                </div>
```

To translate this into the component, the component could have a binding property called `uifOnToggle`, the implemetation could then be:
`<uif-toggle uif-label-off="Don't Upload" uif-label-on="Upload" ng-model="myModel" uif-on-toggle="myToggleHandlingFunction()"/>`
and `ng-change="uifOnToggle()"` could be placed on the `<input>` element in the toggle components template.

**Comment by ghost** [comment]
Wouldn't this apply to all of our directives @andrewconnell ?

For Toggle: I would say we should expose ng-change as an attribute, and pass that internally to the input. No need to create a new attribute. 
Same for ng-true-value and ng-false-value.
I'm very busy at the moment, are you able to submit a PR @sjclemmy ?

**Comment by sjclemmy** [comment]
@rolandoldengarm So like this: `<uif-toggle uif-label-off="Don't Upload" uif-label-on="Upload" ng-model="myModel" ng-change="myToggleHandlingFunction()"/>`

I'd be happy to do the change and submit PR.

**Comment by sjclemmy** [comment]
@rolandoldengarm  Just to let you know I've started dev on this.

**Comment by ghost** [comment]
Good stuff @sjclemmy :+1:

**Comment by sjclemmy** [comment]
I have just tried to implement this with my recent changes in a production app and I have come across a timing issue. I have to wrap the resolved function from ngChange in a $timeout in order for it to get access to the the correctly updated value of ngModel. It's basically 1 cycle behind.
I think this answer explains the problem:
http://stackoverflow.com/questions/33178205/ngchange-fires-before-value-makes-it-out-of-isolate-scope#answer-33181139.

My app wraps this directive in another directive so a simple implementation in a controller may not expose this issue.
