### ISSUE TITLE
Component to create: MessageBanner

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#299]
Official link to component description & demo: http://dev.office.com/fabric/components/messagebanner

Screenshot of web analytics for the original http://officeuifabric.com site by @andrewconnell. Use this to see what are the most popular components: http://imgur.com/gallery/buUcyQv

**Comment by andikrueger** [comment]
I would suggest specs like these:

**specs:**
`<uif-message-banner uif-action="onLabelClick(params)" uif-action-label="Your action label" uif-is-open="true|false" uif-message="Your Message" />`

**&lt;uif-message-banner&gt;**
- @property {Function} uifAction       - Expression to be called on the button click event
- @property {string} uifActionLabel    - Label for the action button.
- @property {string} uifMessage        - Message text
- @property {boolean} uifIsOpen        - Hide or show message banner

I setup a very basic implementation that can be found here: [https://github.com/andikrueger/ng-officeuifabric/tree/issue-299-messagebanner](https://github.com/andikrueger/ng-officeuifabric/tree/issue-299-messagebanner)

I would appreciate hearing your opinion on this.

**Comment by s-KaiNet** [comment]
For `uifMessage` consider rich text option. For example what if the user wants to include bold text or icon in addition to regular text? You can take a look into the contextual menu directive as an example.  
For example: 

``` html
<uif-message-banner>
    <uif-content>
        <uif-icon uif-type="alert"></uif-icon> <b>Important message goes here</b>
    </uif-content>
</uif-message-banner>
```

`<uif-content>` is a directive I used for contextual menu.  
Also it may be handy to have on-close callback. For example perform some action when banner closed.  
All other LGTM

**Comment by andikrueger** [comment]
Thank you for bringing this up. Good point indeed. I'll have a look at it and check if `<uif-content>` impacts the message banner rendering. I'll let you know. 

The on-close callback would be handy. 👍

**Comment by andikrueger** [comment]
@s-KaiNet: I updated my branch with your great input. uif-content is now supported.

**Comment by andikrueger** [comment]
Updated specs:
**Message as plain text**

``` html
<uif-message-banner 
uif-action="customFunction()" 
uif-action-label="Button label" 
uif-is-visible="true|false"
uif-message="message" 
uif-on-close="customCloseFunction()"/>
```

**Message as formatted text**

``` html
<uif-message-banner 
uif-action="customFunction()" 
uif-action-label="Button label" 
uif-is-visible="true|false" 
uif-on-close="customCloseFunction()">
            <uif-content>
                <b>Some formatted content</b> Lorem ipsum
            </uif-content>
</uif-message-banner>
```

**Attributes**
- uif-action {function}: function to be called on button click
- uif-action-label {string}: Label for the action button
- uif-is-visible {boolean}: Hide or show message banner
- uif-message {string}: Messagetext / Alternative uif-content
- uif-on-close {function}: callback function on message banner close

Currently the branch misses tests. Directive and demo look complete to me.

**Comment by andrewconnell** [comment]
I suggest removing the `uif-message` attribute... just make the developer use the `uif-content` for formatted / unformatted text. No need to have both.

Otherwise LGTM.
