### ISSUE TITLE
Cannot click on top of the placeholder text to activate control in uif-textfield

### ISSUE THREAD

**Issue by wobba** [ngOfficeUIFabric/ng-officeuifabric#305]
`<uif-textfield placeholder="This is the placeholder" />`
### Expected Behavior

When clicking anywhere in the text field the placeholder text should dispensary
### Actual Behavior

Click to the right or below the text activates the control. Clicking on the text itself does nothing.
### Steps to Reproduce Behavior

Drop a textfield control with a placeholder in your app. Try to click on top of the placeholder text to activate the text.

**Comment by andikrueger** [comment]
The placeholder hides the input element in a way the input focus event does not fire.

Maybe something like this could be a way to a solution:
`<label ng-show="labelShown" class="ms-Label" ng-click="labelClick()">{{uifLabel || placeholder}}</label>`

and handle the label click in this way:
`scope.labelClick = function(ev: any): void{
  if (scope.placeholder) {
    // focus input
  }
};`

**Comment by wobba** [comment]
I did this on the label using jQuery: 

> onclick="jQuery(this).next().focus()"

passing focus to the underlying input control, so the same thing you describe.

**Comment by andikrueger** [comment]
I created a new branch: [https://github.com/andikrueger/ng-officeuifabric/tree/issue-305-textfield-placeholder](https://github.com/andikrueger/ng-officeuifabric/tree/issue-305-textfield-placeholder)
I think it's working as expected. Please have a look and let me know.
