### ISSUE TITLE
Support for new panel type in Fabric 2.4.x & uifPanel animation issues

### ISSUE THREAD

**Issue by ghost** [ngOfficeUIFabric/ng-officeuifabric#307]
Fabric 2.4.x bring a new [panel type](https://github.com/OfficeDev/Office-UI-Fabric/pull/499). Support for this needs adding to `<uif-panel>`

> _IGNORE THIS... see [comment below](https://github.com/ngOfficeUIFabric/ng-officeuifabric/issues/307#issuecomment-220970945) for details: Furthermore, the animations on the demo site for uifPanel are not working as expecting & need investigation as the panel's `<uif-command-bar>` should animate downwards and panels should slide in and out, as per the (demo site)[http://dev.office.com/fabric/components/panel]. The appropriate classes are being added, but animations aren't working._

**Comment by ghost** [comment]
> _IGNORE THIS... see [comment below](https://github.com/ngOfficeUIFabric/ng-officeuifabric/issues/307#issuecomment-220970945) for details_

The issue with animations looks to be an issue between 2.1.0 and 2.2.0 of Fabric, see plunks below. Animations stopped working in 2.2.0, [dev.office.com](http://dev.office.com/fabric/components/panel) also has the same issue. I'll file a bug in the Fabric repo before I do anything else. 

## 2.2.0

Panel opens quickly, and doesn't close correctly. 

https://embed.plnkr.co/Pn94Jt50QC2HvDCnjQUP/

## 2.1.0

Panel animates in and out correctly

https://embed.plnkr.co/MjHix8BdhLpDYpG1Amqy/

**Comment by andrewconnell** [comment]
Let's only consider the addition of the additional panel type in this issue as there's a recognized bug in the Office UI Fabric https://github.com/OfficeDev/Office-UI-Fabric/issues/505 for the animation stuff that's not something for us to handle. 

As such, I'm going to modify your comments...

**Comment by jjczopek** [comment]
I think there is more to fix on panel directive. I wanted to take a stab at the new panel type, but noticed also one other thing. `uif-type` has following allowed values: `small|medium|large|extralarge|left`. 

Inside the directive [L149](https://github.com/ngOfficeUIFabric/ng-officeuifabric/blob/master/src/components/panel/panelDirective.ts#L149) value of `uif-type` is used to build the class that should be applied to an element, but it's taking the attribute value as is, which results in class name e.g. `ms-Panel--medium`, but that is not valid class for panel, it should be `ms-Panel--md` for medium panel.

**Comment by ghost** [comment]
This changed between releases of Fabric, I believe to conform with naming conventions for other sizes. You should just need to change the PanelType enum to reflect this

**Comment by jjczopek** [comment]
I would say rather add a logic that maps `uif-type` value to proper class names, to stay consistent with other components. 

Also wondering how to tackle the new type of panel. I see two options:
- add additional attribute called `uif-panel-fixed` - if present, it would apply additional class to the element if type is `large`
- add additional type value `largeFixed` due to the fact that `fixed` only applies to large panels (if I understand correctly).

**Comment by ghost** [comment]
@jjczopek, I've added the correct panels and taken into account what you said about the mapping logic. 

I left out the largeFixed changes you proposed because 

a) We didn't decide which was the best approach (`largeFixed`) gets my vote
b) I couldn't find this new panel type in the Fabric repo

if you want to pick that up, then great :)
