### ISSUE TITLE
Support for new table type in Fabric 2.4.x

### ISSUE THREAD

**Issue by waldekmastykarz** [ngOfficeUIFabric/ng-officeuifabric#308]
Fabric 2.4.x introduces a new table type (fixed). This new feature should be added to the `<uif-table>` directive. More information about the new table type is available at https://github.com/OfficeDev/Office-UI-Fabric/pull/493.

Proposed solution: add a new attribute called `uif-table-type` with possible values: `fluid` and `fixed`. For the `fixed` value the new `ms-Table--fixed` CSS class is added to the `table` tag.

**Comment by andikrueger** [comment]
I pushed a new branch at [https://github.com/andikrueger/ng-officeuifabric/tree/issue-308-table-fixed](https://github.com/andikrueger/ng-officeuifabric/tree/issue-308-table-fixed) . @waldekmastykarz  Would you please be so kind and have a look at it?

**Comment by waldekmastykarz** [comment]
Will do! Awesome that you picked it up so quickly 😄

**Comment by waldekmastykarz** [comment]
Just had a quick look:
- there a few typos for the word `fluid`. You can easily find them by going through the changes in your commit
- currently the newly added `ms-Table--fixed` class doesn't do anything as ng-officeuifabric uses Office UI Fabric v2.3.0 whereas the new class has been added in v2.4.0. It would be great to update the whole project to v2.4.0 but I don't know how much work that would be. How do we usually go about that @andrewconnell?
- great to see that you've followed the existing design and included enum, invalid values checking, tests, etc. 👍 

Overall great contribution and I hope we can get it merged quickly. Thanks for participating! 😄

**Comment by andrewconnell** [comment]
Fairly certain there’s nothing holding us from going to 2.4.0… Just need to update package.json and run a test of everything. I’d say just submit this and include a message in the commit that it requires 2.4.0. I’ll see it and make sure it doesn’t get merged => dev & master until we make that update.
