### ISSUE TITLE
uif-button ng-disabled not working properly

### ISSUE THREAD

**Issue by s-KaiNet** [ngOfficeUIFabric/ng-officeuifabric#319]
### Expected Behavior

When using ng-disabled attribute on uif-button, the button should reflect the state. 
### Actual Behavior

It works as expected only if scope property name controlling disabled state equals to `"disabled"`
In other case js error is thrown by angular.

**Comment by andrewconnell** [comment]
Eek... good catch by @tom2all ... more details here: https://github.com/ngOfficeUIFabric/ng-officeuifabric/issues/268#issuecomment-215083711
