### ISSUE TITLE
Component to create: personacard

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#32]
Official link to component description & demo: http://dev.office.com/fabric/components/personacard

_Screenshot of web analytics for the original http://officeuifabric.com site by @andrewconnell. Use this to see what are the most popular components: http://imgur.com/gallery/buUcyQv_

**Comment by jjczopek** [comment]
Let me get this one as well ;) Yet I think it'll take couple more hours than label ;)

**Comment by andrewconnell** [comment]
Sounds good!

**Comment by jjczopek** [comment]
Main specs:

``` html
<uif-persona-card uif-style="round" uif-presence="available" uif-size="xlarge" 
uif-primary-text="Alton Lafferty" uif-secondary-text="Interior Designer, Contoso" 
uif-tertiary-text="Office: 7/1234" uif-optional-text="Available - Video capable">
    <uif-persona-card-action uif-type="chat">
        <uif-persona-card-detail-line>
            <uif-persona-card-detail-label>Lync:</uif-persona-card-detail-label> <a class="ms-Link" href="#">Start Lync call</a>
        </uif-persona-card-detail-line>
    </uif-persona-card-action>
    <uif-persona-card-action uif-type="phone">
        <uif-persona-card-detail-line>
            <uif-persona-card-detail-label>Personal:</uif-persona-card-detail-label> 555.206.2443
        </uif-persona-card-detail-line>
        <uif-persona-card-detail-line>
            <uif-persona-card-detail-label>Work:</uif-persona-card-detail-label> 555.929.8240
        </uif-persona-card-detail-line>
    </uif-persona-card-action>
    <uif-persona-card-action uif-type="video">
        <uif-persona-card-detail-line>
            <uif-persona-card-detail-label>Skype:</uif-persona-card-detail-label> <a class="ms-Link" href="#">Start Skype call</a>
        </uif-persona-card-detail-line>
    </uif-persona-card-action>
    <uif-persona-card-action uif-type="mail">
        <uif-persona-card-detail-line>
            <uif-persona-card-detail-label>Personal:</uif-persona-card-detail-label> <a class="ms-Link" href="mailto:alton.lafferty@outlook.com">alton.lafferty@outlook.com</a>
        </uif-persona-card-detail-line>
        <uif-persona-card-detail-line>
            <uif-persona-card-detail-label>Work:</uif-persona-card-detail-label> <a class="ms-Link" href="mailto:alton.lafferty@outlook.com">altonlafferty@contoso.com</a>
        </uif-persona-card-detail-line>     
    </uif-persona-card-action>
    <uif-persona-card-action uif-type="org">
        <!-- <uif-orgchart></uif-orgchart> -->
    </uif-persona-card-action>
    <uif-persona-card-action uif-type="overflow">
        View profile on Delve
    </uif-persona-card-action>
</uif-persona-card>
```

Above is supposed to render persona card as in [PersonaCard](http://dev.office.com/fabric/components/personacard) example.

Attributes for `uif-persona-card`:
- `uif-style` - round, square. Defaults to round. Same as in `uif-persona`.
- `uif-presence` - available, away, blocked, busy, dnd, offline. Defaults to offline. Same as in `uif-persona`.
- `uif-size` - xsmall, small, medium, large, xlarge. Defaults to medium. Similar to `uif-persona`, but _tiny_ is not a valid size for _persona-card_
- `uif-image-url` - picture URL, if not set show default persona image. Same as in `uif-persona`.
- `uif-primary-text`, `uif-secondary-text`, `uif-tertiary-text`, `uif-optional-text` - optional attributes (similar to `uif-persona`)

`uif-persona-card-detail-line`:
In details section, each line is wrapped with a `div` element with specific CSS. This directive is supposed to provide this wrapping experience.
Attributes:
- `uif-type` - chat, phone, video, mail, org, overflow. This is required attribute. Each action type can be added/used only once per persona-card instance.

`uif-persona-card-detail-label`:
In detail lines, users might like to provide labels for their content. Those labels in Fabric are `span` elements with specific CSS. This directive is supposed to provide this wrapping experience.

Discussion points:
- above spec assumes that there will be limited action types to choose from. Yet on persona card, action is basically an icon and arbitrary HTML content that will be transcluded. My question is - shall we limit the actions or give users flexibility to define their owns, by providing the icon type they would like to use?

Feedback appreciated.

**Comment by ghost** [comment]
I'd say don't limit it. Just accept any. But, may be reanme it to uif-icon instead of uif-type?

**Comment by waldekmastykarz** [comment]
It seems like we use two different approaches for the primary, secondary, tertiary and optional text: in persona and personacard we define them as attributes while in the list we defined them as elements (https://github.com/ngOfficeUIFabric/ng-officeuifabric/issues/24). It would be better if we used the same approach across all directives.

I agree with @rolandoldengarm that actions shouldn't be an enum but we should support any icon instead. That would give us more flexibility in the end.

One thing that's confusing is how the orgchart has been implemented in Office UI Fabric. It has a specific orgchart class that defines its positioning on the card (top right corner). The question is whether orgchart is a fixed component or whether we want to be able to put other actions there as well meaning that we would need a way to distinguish between regular actions and the top-right-corner action.

For the actions links in the detail line: shouldn't we use uif-link (#23) for this instead?

**Comment by jjczopek** [comment]
Ad. 1) I'm flexible here, and can go both ways. Let's see in which direction this goes.

Ad. 2) I think I could introduce another parameter to `uif-persona-card-action` directive, called e.g. `uif-placeholder` - regular, topright, overflow, introduce `uif-icon` as a substitute `uif-type`

Ad. 3) I just copied over what is in their example, you will be free to use whatever you like as it will be transcluded.

**Comment by waldekmastykarz** [comment]
:+1:

**Comment by andrewconnell** [comment]
Referring to 1) I prefer elements over attributes so I'd change it in this spec to match what #24 does.

Referring to 2) I like your @jjczopek suggestions / proposals for the 

Referring to 3) I agree with @waldekmastykarz we should use our own link directive here within the detail.

**Comment by jjczopek** [comment]
Revised spec:

``` html
<uif-persona-card uif-style="round" uif-presence="available" uif-size="xlarge">
    <uif-persona-card-primary-text>Alton Lafferty</uif-persona-card-primary-text>
    <uif-persona-card-secondary-text>Interior Designer, Contoso</uif-persona-card-secondary-text>
    <uif-persona-card-tertiary-text>Office: 7/1234</uif-persona-card-tertiary-text>
    <uif-persona-card-optional-text>Available - Video capable</uif-persona-card-optional-text>
    <uif-persona-card-action uif-icon="chat" uif-placeholder="regular">
        <uif-persona-card-detail-line>
            <uif-persona-card-detail-label>Lync:</uif-persona-card-detail-label> <uif-link ng-href="#">Start Lync call</uif-link>
        </uif-persona-card-detail-line>
    </uif-persona-card-action>
    <uif-persona-card-action uif-icon="phone" uif-placeholder="regular">
        <uif-persona-card-detail-line>
            <uif-persona-card-detail-label>Personal:</uif-persona-card-detail-label> 555.206.2443
        </uif-persona-card-detail-line>
        <uif-persona-card-detail-line>
            <uif-persona-card-detail-label>Work:</uif-persona-card-detail-label> 555.929.8240
        </uif-persona-card-detail-line>
    </uif-persona-card-action>
    <uif-persona-card-action uif-icon="video" uif-placeholder="regular">
        <uif-persona-card-detail-line>
            <uif-persona-card-detail-label>Skype:</uif-persona-card-detail-label> <uif-link ng-href="#">Start Skype call</uif-link>
        </uif-persona-card-detail-line>
    </uif-persona-card-action>
    <uif-persona-card-action uif-icon="mail" uif-placeholder="regular">
        <uif-persona-card-detail-line>
            <uif-persona-card-detail-label>Personal:</uif-persona-card-detail-label> <uif-link ng-href="mailto:alton.lafferty@outlook.com">alton.lafferty@outlook.com</uif-link>
        </uif-persona-card-detail-line>
        <uif-persona-card-detail-line>
            <uif-persona-card-detail-label>Work:</uif-persona-card-detail-label> <uif-link  ng-href="mailto:alton.lafferty@outlook.com">altonlafferty@contoso.com</uif-link>
        </uif-persona-card-detail-line>     
    </uif-persona-card-action>
    <uif-persona-card-action uif-icon="org" uif-placeholder="topright">
        <!-- <uif-orgchart></uif-orgchart> -->
    </uif-persona-card-action>
    <uif-persona-card-action uif-placeholder="overflow">
        View profile on Delve
    </uif-persona-card-action>
</uif-persona-card>
```

`uif-persona-card-detail-line`:
In details section, each line is wrapped with a `div` element with specific CSS. This directive is supposed to provide this wrapping experience.
Attributes:
- `uif-placeholder` - regular, topright, overflow. Determines in which part of the persona-card action should be added.
- `uif-icon` - All available icons are valid. This is required attribute for `regular` and `topright` placeholders, optional for `overflow` placeholder.

**Comment by andrewconnell** [comment]
LGTM

**Comment by jjczopek** [comment]
Task list, for progress monitoring:
- [x] `uif-persona-card-detail-label` directive
- [x] `uif-persona-card-detail-line` directive
- [x] `uif-persona-card-primary-text` directive
- [x] `uif-persona-card-secondary-text` directive
- [x] `uif-persona-card-tertiary-text` directive
- [x] `uif-persona-card-optional-text` directive
- [x] `uif-persona-card` directive
  - [x] main html rendering
    - [x] `uifSize` handling
    - [x] `uifStyle` handling
    - [x] image area
    - [x] `uifPresence` handling
  - [x] transclusion of `uif-persona-card-*-text` directives
  - [x] `uif-persona-card` controller
    - [x] logging capability
  - [x] registering actions on callout automatically
- [x] `uif-persona-card-action` directive

**Comment by jjczopek** [comment]
Oh dear, I think it's finished. Need to write the doc, polish the demo and will be good to go (I think).

**Comment by ghost** [comment]
Good stuff @jjczopek  :+1:
