### ISSUE TITLE
uif-textfield: add support for more input types

### ISSUE THREAD

**Issue by andikrueger** [ngOfficeUIFabric/ng-officeuifabric#323]
`uif-textfield` should support the following input types:
(checked ones are supported by now)
- [x] text
- [x] password
- [ ] email
- [ ] url
- [ ] tel
- [ ] range => add support for attributes: min, max, step
- [ ] number  => add support for attributes: min, max, step

The following type values are optional, as they are more likely to fit into
`uif-datepicker` and `uif-searchbox`:
- [ ] month
- [ ] time
- [ ] week
- [ ] search

**Comment by ghost** [comment]
@andikrueger I've assigned this issue to you, as you seem to be working on it. Okay?

**Comment by andikrueger** [comment]
@rolandoldengarm That's fine.
