### ISSUE TITLE
Component to create: pivot

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#33]
Official link to component description & demo: http://dev.office.com/fabric/components/pivot

_Screenshot of web analytics for the original http://officeuifabric.com site by @andrewconnell. Use this to see what are the most popular components: http://imgur.com/gallery/buUcyQv_

**Comment by jjczopek** [comment]
Let's keep the momentum. Let me handle that one.

**Comment by jjczopek** [comment]
Main sepcs:

``` html
<uif-pivot uif-size="large" uif-type="tabs">
    <uif-pivot-link>My Files</uif-pivot-link>
    <uif-pivot-link>Recent</uif-pivot-link>
    <uif-pivot-link>Shared with me</uif-pivot-link>
    <uif-pivot-ellipsis><uif-pivot-ellipsis>
</uif-pivot>
```
- `<uif-pivot></uif-pivot>` - main directive, renders the container
  - `uif-size` attribute - determines the size of the pivot. `regular|large`, default `regular`
  - `uif-type` attribute - determines the type of the pivot. `regular|tabs`, default `regular`
- `<uif-pivot-link></uif-pivot-link>` - renders pivot link
- `<uif-pivot-ellipsis></uif-pivot-ellipsis>` - renders the ellipsis at the end of the pivot.

Feedback appreciated.

**Comment by ghost** [comment]
I'm not sure what the idea is behind the ellipsis. I guess you should be able to show a menu or something? In the demo I don't see an implementation. 
I'd say that uif-pivot-ellipsis should be able to contain child elements, which are shown if you click on it.

**Comment by s-KaiNet** [comment]
What about selected item?  
All other LGTM.

**Comment by jjczopek** [comment]
@rolandoldengarm: I can do transclusion in ellipsis. Then user could hook an ng-click on the ellipsis that could toggle whatever is inside the ellipsis.

@s-KaiNet: could you elaborate what you mean by "selected item"?

**Comment by s-KaiNet** [comment]
When you click on pivot link it becomes selected. You said that there will be a possibility to track selected item and set initial state. Current spec doesn't have any notion of selected item.

**Comment by jjczopek** [comment]
@s-kainet: what I meant is that pivot maintains its selected state by the css inside - when you click, it adds is-active or is-selected class to the element. Thats what I meant by that. However if you think it might be useful to have such possibility, I'll try to add that.

**Comment by s-KaiNet** [comment]
@Elfayer asked for this functionality, may he can comment smth.

**Comment by Elfayer** [comment]
I'd suggest to do something like what has been done for Angular Material : https://material.angularjs.org/0.11.2/#/api/material.components.tabs/directive/mdTabs

They have a `md-selected` that keeps the "Index of the active/selected tab". This is useful because you can manually change it via your controllers or get the current tab selected via this variable.

**Comment by andrewconnell** [comment]
In that spirit, what about `uif-selected` which returns the actual pivot link object, or the object the pivot link is bound to rather than the index? Returning an index is a PITA IMHO because then the developer needs to figure out which pivot link matches that index number.

This proposed attribute could then also accept setting the pivot link object or the object the pivot link is bound to.

**Comment by jjczopek** [comment]
@andrewconnell  I haven't considered adding any additional and I'm not really sure what such object should contain - index, & label text? Some kind of value? If user would like to select the option from the code, he should then pass an object rather than just an index?

**Comment by andrewconnell** [comment]
That's how I'd expect it to work. If I want the selected item, I want the object to come back that is represented by that thing... same in reverse: if I give the `uif-selected` attribute an object, I expect it to find that object in the collection of pivots and select it. Does that make sense?

**Comment by jjczopek** [comment]
You want to be able to map any object into pivot, or it should be fine when I come up with a fixed structure that should be used?

**Comment by andrewconnell** [comment]
I might be suggesting something that's better as an enhancement in the future. Maybe punt what I'm suggesting and just build what we have first :) we can enhance it later.

To address your question, not sure I understand the question... I get without binding a collection of items to the pivot a developer can use the `ng-repeat` to write out the pivot "tabs". What I"m proposing is being able to do something like this:

`<uif-pivot uif-type="tabs" uif-pivots="{{pivotCollection}}" uif-selected="{{pivotCollection[3]"></uif-pivot>`

The thing I don't like (_IMHO_) about the Angular Material implementation is that they make you get the index and then figure out which one is selected... but it's always a two step process in (1) get the index of the selected one (2) figure out which is index N. Maybe it's just me, but seems like a silly middle step.

**Comment by jjczopek** [comment]
Got it. I like the spec. `uif-selected` will always hold the reference to the item currently selected.

``` html
<uif-pivot uif-size="large" uif-type="tabs" uif-pivots="pivotCollection" uif-selected="selectedPivot">
    <uif-pivot-ellipsis><!-- ContextMenu --><uif-pivot-ellipsis>
</uif-pivot>
```

**Comment by andrewconnell** [comment]
Hey... we have an issue with this directive. I merged it without checking everything... now I see the code coverage is showing below 50% for tests... see this build report: 

https://circle-artifacts.com/gh/ngOfficeUIFabric/ng-officeuifabric/115/artifacts/0/tmp/circle-artifacts.UPLlyLE/code-coverage/index.html

I'm going to open an issue on this one as it's just well below all the other directives.
