### ISSUE TITLE
ng-model does not work with uif-searchbox

### ISSUE THREAD

**Issue by deval-github** [ngOfficeUIFabric/ng-officeuifabric#338]
I have used the uif-searchbox directive in my sharepoint hosted app for filtering data displayed in the uif-table component.
To filter the data on the basis of text in serach box with uif-searchbox directive we need to bind the text in ng-model. So that later a filter can be applied on that basis
But uif-searchbox does not seem to support ng-model.
If this is true then is there a way on how the data can be filtered without using ng-model in uif-searchbox. If possible please give an example.

**Comment by andikrueger** [comment]
If I understand you correctly, you’re saying that uif-searchbox does not support the attribute ngModel. That's true - uif-searachbox uses the attribute `value`, which binds to ng-model.

Have a look at this [plnkr](https://plnkr.co/edit/ewLsq3?p=preview).

Usage:

``` html
<uif-searchbox value="value" placeholder="placeholder"></uif-searchbox>
```

**Comment by deval-github** [comment]
Hello andikrueger,

Thanks a lot for the reply.
It cleared the doubt. :+1:
