### ISSUE TITLE
Component to create: MessageBar

### ISSUE THREAD

**Issue by ghost** [ngOfficeUIFabric/ng-officeuifabric#339]
MessageBanner is in the latest release (2.6.0) of Office UI Fabric. Not on dev.office.com yet. 

See: https://github.com/OfficeDev/Office-UI-Fabric/pull/515 and https://github.com/OfficeDev/Office-UI-Fabric/releases/tag/2.6.0

**Comment by andikrueger** [comment]
I would suggest the following specs:

``` html
<uif-message-bar type="Error|Remove|SevereWarning|Success|Warning|NONE">
  <uif-content>
    lorem ipsum dolor sit amet, a elit sem interdum consectetur adipiscing elit
  </uif-content>
  <uif-link ng-href="http://ngofficeuifabric.com">Link text</uif-link>
</uif-message-bar>
```

Plnkr with a messagebar demo: [DEMO](https://plnkr.co/edit/o7ZICu?p=preview)

**Comment by jjczopek** [comment]
I would change `type`to `uif-type`. It should be an enum with following values:
`error|remove|severewarning|success|warning`. By default it's not specified.

I'm ok with the rest.

I could take that one as I actually was missing this feature on my project.

**Comment by andikrueger** [comment]
Thanks for your input.
I absolutely agree on the `type` as `uif-type` thing. I'm already half way through with the directive. I already started working on it... :)

**Comment by andikrueger** [comment]
@jjczopek I published my dev-branch. Would you give it a try?

**Comment by andikrueger** [comment]
I could not use `uif-icon` in the directive, because there are two classes needed to render the icons properly. Mabe this could result in a feature request for `uif-icon`.
