### ISSUE TITLE
Component to create: progressindicator

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#34]
Official link to component description & demo: http://dev.office.com/fabric/components/progressindicator

_Screenshot of web analytics for the original http://officeuifabric.com site by @andrewconnell. Use this to see what are the most popular components: http://imgur.com/gallery/buUcyQv_

**Comment by johnmeilleur** [comment]
**SPEC**

First thoughts...

main component directive: `<uif-progressindicator />`
optional string attribute `uif-name`: renders the name above the progress indicator
optional string attribute `uif-description`: renders the description below the progress indicator
optional string attribute `uif-percentcomplete`: a number between (inclusive) 0 and 100 that renders the progress bar

examples:
`<uif-progressindicator uif-name="mydocument.docx" uif-description="This is a sample document" uif-percentcomplete="65" />`

**Comment by andrewconnell** [comment]
I take it you want to grab this after `uif-overlay` is done?

Also, should be `uif-percent-complete`... this should also raise an error if it's outside the 0-100 range & if it's not a number that's passed in (your spec says _string_)

Otherwise looks good.

**Comment by johnmeilleur** [comment]
Yes.  Just getting my feet wet. :)

**Comment by waldekmastykarz** [comment]
Shouldn't it be `uif-progress-indicator` by the way?

**Comment by andrewconnell** [comment]
IMHO makes more sense to use `uif-percent-complete` to indicate how full the bar is if we're using numbers.

**Comment by waldekmastykarz** [comment]
Oh I meant naming the directive `uif-progress-indicator` rather than `uif-progressindicator` to consistently separate words. Progress should be indicated using the `uif-percent-complete` attribute on the directive as you mentioned.

**Comment by andrewconnell** [comment]
oh yes... good call @waldekmastykarz

**Comment by waldekmastykarz** [comment]
:+1:

**Comment by johnmeilleur** [comment]
Submitted PR with incorporated feedback.

Would like to see if I can animate the progress bar when moving between states (e.g. 10% to 30%).

@andrewconnell please change label to work in progress

**Comment by johnmeilleur** [comment]
Ready for review - PR #104
