### ISSUE TITLE
MessageBar: uif-type binding not working properly

### ISSUE THREAD

**Issue by andikrueger** [ngOfficeUIFabric/ng-officeuifabric#356]
### Expected Behavior

uif-type should be able to bind to a function or a scope variable value
### Actual Behavior

uif-type binding does not work as expected
### Steps to Reproduce Behavior

https://plnkr.co/edit/wImWYb2UwUn5jF23Wsji?p=preview

**Comment by jjczopek** [comment]
Honestly speaking none or at least most of the components does not support this. At least those that I have been working on - spinner, callout, persona, personaCard, pivot...

**Comment by andikrueger** [comment]
This also crossed my mind after I had opened the issue.
I think we should discuss this topic further to have a consistent support/implementation for this kind of issue. 

In this certain kind I expected to pass a dynamic message and type into the directive to give the user timely information underneath an input element depending on the input value...

**Comment by andrewconnell** [comment]
Then let's have the discussion. @andikrueger care to spin up a new issue to discuss it more in general? Personally I think the issue needs to be described & articulated a bit more... just like the `disabled` & jQuery testing issues we ran into earlier... now is the time to have this discussion.

**Comment by jjczopek** [comment]
I'm wondering if that's actually necessary. IMHO that this kind of attributes (type, size etc) that take string values should have those attributes properly watched in the directive and react to changes of the attribute values. And when it's needed to change the attribute value, change the scope value by a watch expression maybe on a controller level?

**Comment by andrewconnell** [comment]
So that’s sort of what I was thinking as I read the issue as I was having a hard time remembering a scenario where I bound a function to an attribute rather than just binding the poperty on the model to the attribute.

**Comment by jjczopek** [comment]
In that particular case, the problem is that the `uif-type` attribute is configured on the directive scope as expression, and angular tries to evaluate it, and fails on `{{}}` construct. 

In other directives attributes expect string value (denoted by the `@` on the isolated scope definition), and Angular seeing that first will interpolate value inside `{{}}` and then pass the resulting string value for further processing.

Expect PR any minute now.
