### ISSUE TITLE
$dirty not being set on uif-dropdown

### ISSUE THREAD

**Issue by ghost** [ngOfficeUIFabric/ng-officeuifabric#368]
Refer to https://github.com/ngOfficeUIFabric/ng-officeuifabric/issues/361 for more information.

**Comment by andrewconnell** [comment]
See repo: http://plnkr.co/edit/vulKP4uZCmJ6YUiBrwiT?p=preview

**Comment by jjczopek** [comment]
Actually it seems that $dirty is working correctly for the uif-dropdown. If you add `name` attribute to the drop-down, it will show up in the JSON output in the plunk. When you change value, `$dirty` is set properly on the underlying ngModel. However `$touched` is not set properly. Refer to forked plunk: http://plnkr.co/edit/MQWaFsOi12dVD63O239y?p=preview

I will submit PR soon that takes care of the $touched not being set and adds test cases for both `$touched`& `$dirty` being properly set.
