### ISSUE TITLE
uif-table: can't select all rows via table header row

### ISSUE THREAD

**Issue by andikrueger** [ngOfficeUIFabric/ng-officeuifabric#369]
### Expected Behavior

When allowing to select multiple rows it is possible to toggle selection of all rows using the table row selector () in the header row. If not all rows are selected, clicking the table row selector will select all rows. If all rows are selected, clicking it will deselect all rows.
### Actual Behavior

[Demo](http://ngofficeuifabric.com/demos/uifTable/)
See: Selecting multiple rows (<uif-table uif-row-select-mode="multiple">)

**Comment by ghost** [comment]
I can't select _any_ row... 
@waldekmastykarz are you able to comment?

**Comment by andikrueger** [comment]
I'll open a PR as soon as the test error has been fixed #417.

**Comment by andrewconnell** [comment]
I'm stuck on the issues with breadcrumb tests... see the message I left in Slack today. I'm thinking about just commenting the failing tests out so it doesn't block anyone else, like you submitting a PR for this.
