### ISSUE TITLE
uif-datepicker unable to handle null values

### ISSUE THREAD

**Issue by djeffa** [ngOfficeUIFabric/ng-officeuifabric#372]
I'm having a datasource that returns null in case a datetime field is empty. This results in the following error when the form loads:
angular.js:13236 TypeError: Cannot read property 'getFullYear' of null
    at e.setValue (ngOfficeUiFabric.min.js:9)
    at o.$render (ngOfficeUiFabric.min.js:9)
    at ngModelWatch (angular.js:26472)
    at Scope.$digest (angular.js:16655)
    at angular.js:16859

Had a quick look and it seems the bound value is only checked for empty strings and undefined:
`DatepickerDirective.prototype.postLink = function ($scope, $element, attrs, ctrls) {`
`var datepickerController = ctrls[0];`
`var ngModel = ctrls[1];`
`datepickerController.initDatepicker(ngModel);`
`ngModel.$render = function () {`
`if (ngModel.$modelValue !== '' && typeof ngModel.$modelValue !== 'undefined') {`
`if (typeof ngModel.$modelValue === 'string') {`
`var date = new Date(ngModel.$modelValue);`
`datepickerController.setValue(date);`
`}`
`else {`
`datepickerController.setValue(ngModel.$modelValue);`
`}`
`}`

Is it possible that a null check is also added here?

[Plunker link](https://plnkr.co/edit/KsgPJtPU6Tl6NvGPQblV?p=preview)

**Comment by andrewconnell** [comment]
As the issue template indicated when you created the issue, could you reproduce it with a plunkr or something? Easier to see what's going on and see if it's a bug / feature request. 

But yes, a null check could get added. Why don't you fork & submit a PR?

**Comment by djeffa** [comment]
Sorry about that, added a plunker link to demonstrate the issue. The problem occurs on first load and after setting the value to null later.

Haven't worked with git before, but i'll figure it out and submit a PR when i have some spare time.
