### ISSUE TITLE
$dirty not being set on uif-commandbar

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#376]
Refer to #361 for more information.
### Steps to Reproduce Behavior

http://plnkr.co/edit/qzfvrxDRYh0CmVEzPQtH?p=preview

**Comment by jjczopek** [comment]
Should command bar actually be considered as a component used in forms? For me at least it  does not make much of a sense. 

Also on the demos we have right now on the website, it doesn't look like the component even intends to be leverage ng-model. It's leveraging ng-click and custom binding of the search term.

IMHO this $dirty not being set issue is not applicable to uif-commandbar.

**Comment by andrewconnell** [comment]
Agreed with @jjczopek ... closing this as not relevant.
