### ISSUE TITLE
$dirty not being set on uif-searchbox

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#378]
Refer to #361 for more information.
### Steps to Reproduce Behavior

http://plnkr.co/edit/5jdSQEUfLo6yR9zlNAJH?p=info

**Comment by brannmar** [comment]
Any updates on this one?

**Comment by andrewconnell** [comment]
ATM no… sorry but the team is working through various bugs & adapting to changes from the Office UI Fabric team…
