### ISSUE TITLE
Component to create: toggle

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#38]
Official link to component description & demo: http://dev.office.com/fabric/components/toggle

_Screenshot of web analytics for the original http://officeuifabric.com site by @andrewconnell. Use this to see what are the most popular components: http://imgur.com/gallery/buUcyQv_

**Comment by andrewconnell** [comment]
Started by @rolandoldengarm ...

**Comment by ghost** [comment]
Will work on it next week :)

**Comment by rolandoldengarm** [comment]
Submitted PR. https://github.com/ngOfficeUIFabric/ng-officeuifabric/pull/65
