### ISSUE TITLE
Adding ng-controller to a ng-officeuifabric directive breaks it. Wrong design?

### ISSUE THREAD

**Issue by ladaltamirano** [ngOfficeUIFabric/ng-officeuifabric#380]
Testing on

```
   "dependencies": {
      "angular": "1.5.5",
      "angular-animate": "1.5.5",
      "angular-sanitize": "1.5.5",
      "ng-office-ui-fabric": "0.12.0",
      "office-ui-fabric": "2.6.1"
   }
```

And running

```
     "name": "ngofficeuifabric.github.io"
     "version": "0.12.0"
```
### Steps to Reproduce Behavior

I added an ng-controller to the `<uif-message-bar>` tag at /demos/uifMessageBar/ and it breaks it
### Expected Behavior

This shouldn't happend at all. It should be able to work right straightforward. Wrong design?
### Actual Behavior

Outputs code: {{ name }}

**Comment by andrewconnell** [comment]
Can you create a plunker showing this repo'd, just like the template mentioned when you created this issue? If all you did was what you describe in the issue, that's not going to be enough as you're also going to need to create a controller and attach it by name.

**Comment by andrewconnell** [comment]
Closing due to no response...
