### ISSUE TITLE
uifFacePile always displays overflow text

### ISSUE THREAD

**Issue by newq** [ngOfficeUIFabric/ng-officeuifabric#381]
uifFacePile always displays overflow text even if limit is not exceeded. 

Example: uiOverFlowLimit is set to 5, and we have 3 people in the array. Then the overflow text is _+-2_.

_update: submitted PR with fix._

**Comment by andrewconnell** [comment]
AUTORESPONSE: Help us help you... do you have a bug you're posting? If you make it easy for us to repo, we can triage and if necessary, address it quicker. Ideally, you submit a PR with a new test that fails demonstrating the issue. Or per the [issue template](https://github.com/ngOfficeUIFabric/ng-officeuifabric/blob/master/.github/ISSUE_TEMPLATE.md) that this issue defaulted to when you created it, please update this issue with a plunk / jsfiddle / codepen repo this issue.

**Comment by newq** [comment]
Plunker demonstrating the bug: [http://embed.plnkr.co/8IhxbiRKW63ILQnBw6Tv/](http://embed.plnkr.co/8IhxbiRKW63ILQnBw6Tv/)

**Comment by ghost** [comment]
Looks like @newq has submitted a PR for this in #383
