### ISSUE TITLE
uifButton - value of disabled attribute is ignored

### ISSUE THREAD

**Issue by newq** [ngOfficeUIFabric/ng-officeuifabric#384]
### Expected Behavior

`disabled="true"` should disable the button.
`disabled="false"` should not disable the button.
### Actual Behavior

button is always disabled if attribute `disabled` is present.
### Steps to Reproduce Behavior

plunker to demonstrate the issue
[https://plnkr.co/edit/JDfb1NEVQBJRBOoPC2vv?p=preview](https://plnkr.co/edit/JDfb1NEVQBJRBOoPC2vv?p=preview)
### Additional Thoughts

Alternatively `ng-disabled` attribute could be supported?

**Comment by andrewconnell** [comment]
That's not how the HTML `disabled` attribute works. If `disabled` is present, that means you want to disable the item... regardless if you set its value. This works as designed: 

See: http://www.w3schools.com/tags/att_input_disabled.asp

**Comment by andrewconnell** [comment]
This works as designed... the HTML spec says that regardless of the value you set, if `disabled` is present, that measn you want to disable it: http://www.w3schools.com/tags/att_input_disabled.asp

**Comment by newq** [comment]
You are right of course, regarding the HTML spec. That's why I proposed supporting`ng-disabled` like angular does on the `button` tag. Would it be acceptable then if I created an issue for it? How would you implement a uif-button that could be disabled via a scope variable?

**Comment by andrewconnell** [comment]
If I recall, `ng-disabled` should be respected. You're saying it isn't?
