### ISSUE TITLE
Add `type="button"` to `uif-callout` use of `uif-button`

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#387]
See issue #374 for discussion

**Comment by jjczopek** [comment]
@andrewconnell: some clarification is needed here. Callout directive itself does not leverage `uif-button` directive. `uif-button` is used in demos for the callout, but not on the directive itself. If callout is supposed to have close button, it's added to the markup of the directive on runtime like this:

``` ts
      let closeButtonElement: ng.IAugmentedJQuery = ng.element(
        '<button class="ms-Callout-close" type="button">' +
        '<i class="ms-Icon ms-Icon--x"></i>' +
        '</button>');
```

And when it comes to action buttons, I think it should be the responsibility of the user/developer to add `type=button` if he wants to use `uif-button` as the action on the callout. 

One action point here I believe actually would be to add `type=button` to callout demos to provide good example to developers.

**Comment by ghost** [comment]
Looking at the code, and my original post in #374, no change to the directive is required here. Changing the demo would be a good idea though

**Comment by andrewconnell** [comment]
Agreed... seems like this issue was created but wasn't necessary.
