### ISSUE TITLE
Add type="button" to uifDialog

### ISSUE THREAD

**Issue by ghost** [ngOfficeUIFabric/ng-officeuifabric#392]
See #374 for more information. `type="button"` needs adding to the `<button>` elements

**Comment by ghost** [comment]
picking back up @andrewconnell, can you change label?

**Comment by andrewconnell** [comment]
I'm going to close this... I think fundamentally we need to revisit the dialog... see #455 ... I think our initial implementation is flawed and overly complex... we should bite the bullet and redo it to match the way the react component works.
