### ISSUE TITLE
Context menu demo is not working

### ISSUE THREAD

**Issue by sivarajanr** [ngOfficeUIFabric/ng-officeuifabric#401]
http://ngofficeuifabric.com/demos/uifContextualMenu/

**Comment by s-KaiNet** [comment]
angular-animate and anuglar-sanitize inclusions are missing for this page. 
Should be exactly the same as for [http://ngofficeuifabric.com/demos/uifNavbar/](http://ngofficeuifabric.com/demos/uifNavbar/)  

@andrewconnell  can you please take a look?

**Comment by andrewconnell** [comment]
My bad... I'll fix in the next demo site update...
