### ISSUE TITLE
grid column not working

### ISSUE THREAD

**Issue by zavier-sanders** [ngOfficeUIFabric/ng-officeuifabric#406]
Hi,

I'm using ng-OfficeUIFabric to create a custom SharePoint 2013 form. For some odd reason, I can only get one "uif-" directive to render within a **column**. This should be pretty straightforward since it's just a grid system, but I'm completely stuck. I can use multiple fields in a column with bootstrap, but with ng-OfficeUIFabric I'm stuck with one. 

Expected Behavior:
I should be able to have multiple fields/directives within a column.

Actual Behavior:
Only one field/directive gets rendered in a column. 

The fields in line 36 and 41 don't get rendered. Nothing gets rendered after the first directives (lines 35 & 40), even if I type plain text. 

![image](https://cloud.githubusercontent.com/assets/11600582/17654999/86c7b598-626e-11e6-974e-6a5cd4b2cb48.png)

I'm really looking forward to developing custom SharePoint forms with ng-OfficeUIFabric and appreciate any help with this issue. 

Thanks

**Comment by ghost** [comment]
Don't use self-closing tags for e.g. uif-textfield. Please try that :)

**Comment by zavier-sanders** [comment]
Thanks @rolandoldengarm !  Removing the self-closing tags worked. 

![image](https://cloud.githubusercontent.com/assets/11600582/17668255/0394930c-62ce-11e6-8e34-03d29af4c2b2.png)

**Comment by andrewconnell** [comment]
This project actually schooled me on that... self-closing tags aren't typically legit. There are a few in HTML that is always shown that way, but Angular exposed that thinking as bad...
