### ISSUE TITLE
Element vs. attribute directives

### ISSUE THREAD

**Issue by waldekmastykarz** [ngOfficeUIFabric/ng-officeuifabric#41]
Looking at @andrewconnell Pen @ http://codepen.io/andrewconnell/pen/MaedKX I've noticed that buttons are defined as a &lt;button>, &lt;div> and &lt;a>. If we use an element directive won't we be dictating which element is rendered rather than allowing developers to choose what makes the most sense for their application? The confusing part is that if you look at the current Fabric samples @ http://dev.office.com/fabric/components/button all buttons are rendered as &lt;button>. Fabric however supports applying the .ms-Button class on any kind of element.

If you look at ngMaterial (https://github.com/angular/material/blob/8ef798f0fe242c555ef7c11fa0abe762fb218a02/src/components/button/button.js) they support both element- and attribute-level usage and default to the &lt;button> element. Is this something that we would like to be doing as well to provide developers with maximum flexibility?

**Comment by andrewconnell** [comment]
I'm just going to implement the `<button>` way of doing it... not the other two ways. No one is using those other options from what i heard from the UI fabric teams.

If the need & justification arises for others, we'll deal with it at that time.
