### ISSUE TITLE
The documentation for <uif-searchbox> is incorrect

### ISSUE THREAD

**Issue by calin-stan** [ngOfficeUIFabric/ng-officeuifabric#413]
On the website, it says to use the "uif-value" attribue but in the implementation, "value" must be used.
I spent a lot of time until I saw that i was using the wrong attribute.

![pasted image at 2016_09_28 05_58 pm](https://cloud.githubusercontent.com/assets/16622833/18944392/01d3d22a-862e-11e6-8d27-6417c9597f95.png)

**Comment by andrewconnell** [comment]
Want to submit a PR for this to give us a hand?

**Comment by calin-stan** [comment]
I could try. I hope I can manage to find the time for this today after work. :)

**Comment by calin-stan** [comment]
I tried to push my branch with the fix but I don't seem to have the correct access rights.

**Comment by andrewconnell** [comment]
You shouldn't have a problem forking the repo, making the change & submitting a PR. This explains it: https://github.com/ngOfficeUIFabric/ng-officeuifabric/blob/master/docs/guides/PULL-REQUESTS.md
