### ISSUE TITLE
Issue with <uif-choicefield> (inconsistency)

### ISSUE THREAD

**Issue by calin-stan** [ngOfficeUIFabric/ng-officeuifabric#416]
There is an inconsistency regarding the way a uif-choicefield responds to clicks.
The "radio" type will accept a click on the entire width of the <uif-choicefield-option> whereas the "checkbox" type will only accept the click on the label and check-box. This can be reproduced on the [live demo](http://ngofficeuifabric.com/demos/uifChoicefield/)

I believe that it would be a good idea to allow choosing if you want the click to be recorded on the full width of the div or only on the label and check-box.

**Comment by andikrueger** [comment]
Here is a plunkr: [Demo](https://plnkr.co/edit/kYYiumTmZvn0yTUcotsM)

The demo for type radio uses the `uif-choicefield-group` element to wrap the `uif-choicefield-option` elements. This enables the elements to accept the click on the full width (Does not depend on radio or checkbox). 
If you use radios without the `uif-choicefield-group` element the type radio accepts the click only on the label and the radio-box too.

Wrapping checkboxes in `uif-choicefield-group` doesn't work as expected. Each checkbox depends on their own model.
Maybe we should change it to something like this: [Checklist-model](https://vitalets.github.io/checklist-model/)

**Comment by andrewconnell** [comment]
I'm not sure any action is required here... I think the `<uif-choicefield-option>` is designed to be wrapped with `<uif-choicefield-group>` element. If you look at the Office UI Fabric, they only list the group option, they don't even have an option for a stand alone choice field option.

As such, I think the our demo should just get up dated to show the intended use.

Thoughts? @andikrueger ?

**Comment by andikrueger** [comment]
The checklist model is more a comfort feature than a real requirement. 

We should showcase the intended usage in the demo and work on with the initial design.
