### ISSUE TITLE
Nuget dependency can't be fulfilled 

### ISSUE THREAD

**Issue by douglasware** [ngOfficeUIFabric/ng-officeuifabric#424]
The latest stable package requires OfficeUIFabric >= 2.6.2, but the latest published on Nuget is 2.6.1.

**Comment by ghost** [comment]
Hmm, 2.6.2 is a Node only release
https://github.com/OfficeDev/office-ui-fabric-core/releases/tag/2.6.2
Don't know why they didn't push it to Nuget.

**Comment by andikrueger** [comment]
2.6.2 was a fix for an issue which prevented the build: https://github.com/OfficeDev/office-ui-fabric-core/issues/821#issuecomment-252625060
And the original issue:
https://github.com/OfficeDev/office-ui-fabric-core/issues/808

I think it's save to change the package.json and require 2.6.1.

**Comment by andrewconnell** [comment]
Fixing now... this is so stupid. Why issue a release and not publish it? If you bump the version, BUMP THE VERSION.

So wait.. they pushed it to NPM, but not NuGet. Is this really a bug for ngOfficeUIFabric?

**Comment by andrewconnell** [comment]
Nevermind... confirmed by the Office UI Fabric guys in https://github.com/OfficeDev/office-ui-fabric-core/issues/824. We won't fix... they screwed up and are fixing it so closing this as a a wontfix.

**Comment by ghost** [comment]
Chill @andrewconnell  👍  :)

**Comment by Jahnp** [comment]
Sorry guys, honest mistake when publishing.

**Comment by andrewconnell** [comment]
NP... caught us off guard but glad it's getting resolved :)

**Comment by Jahnp** [comment]
For sure. I mentioned it in [#824](https://github.com/OfficeDev/office-ui-fabric-core/issues/824), but the package has been uploaded now--hopefully this should be resolved. Please let us know if you hit any other issues with this version.
