### ISSUE TITLE
Each component in it's own module?

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#43]
Question for everyone to weigh in... actually two...

**Q1: Should each component be in it's own Angular module?**
Today it looks like we're doing two... `fabric.ui.components` is defined in `core.ts` that is the root of the entire library, but we also have things like `fabric.ui.components.choicefield` for each one.

> IMHO, `fabric.ui.components` should be renamed to `officefabricui.core` & each component should be in `officefabricui.components.*`.

**Q2: Should we publish the library as a single entity, or each component as it's own in addition to the single entity?**
This goes hand-in-hand with the first question. Angular Material allows for either one... you can grab the entire thing (which injects all the other modules in to the root module that you inject into your app) or you can grab just the components you want, reference the JS files independently (or concat them on your own) and then manually inject only the modules you want rather than the main one.

> IMHO, we should do exactly what Angular Material is doing. We'd have a single module `officeuifabric.components` that would inject all `officeuifabric.components.*`. This would allow someone to grab just one reference & get everything, or selectively grab what they want. We can then publish each component separately on bower the same way that Angular Material does it.
> 
> FWIW, might be a little while until we give people the ability to split them out... for the short term & p1 goal, we just box it up in one package.

**Comment by jjczopek** [comment]
Answering in reverse order. Following the project philosophy, if we want to follow patterns from Angular Material, in the long run I think we should go for it - have packages for each component plus all-in-one. But maybe to keep things simpler at the beginning, let's target one package and then split it up to multiple packages. There are discussions around many aspects and I think this could wait until we have a good base that we can work with.

As per first question, referring to what I suggested above - each component should have it's own module. This way components would be easier to publish as separate entities.

Happy to see other suggestions.

**Comment by s-KaiNet** [comment]
On **Q1** agreed that every component should goes in a single module. This will be in line with angular material, which is very good example, imho, and in line with this great [style guide](https://github.com/johnpapa/angular-styleguide#modularity) (_Modularity_)  
On **Q2** agreed with @jjczopek that we can skip it for a while. If resulting package won't be very heavy, then why do I need to think about how can I download only needed parts if I can grab all the things without a big performance overhead in terms of library size?

**Comment by waldekmastykarz** [comment]
:+1: on @s-KaiNet

**Comment by ghost** [comment]
Also agreed with @s-KaiNet and @jjczopek . I created separate modules to follow Angular Material.
I made up this name fabric.ui.components, but there may be a better name of course :). @andrewconnell  new naming suggestions are fine with me.

**Comment by andrewconnell** [comment]
Good to see everyone is in agreement... cool... thanks folks!

@rolandoldengarm - I am updating the module naming scheme to be more inline with what the Angular Material guys have done for their library.
