### ISSUE TITLE
Is there anyway to disable a list item (uif-list-item)??

### ISSUE THREAD

**Issue by tuanjinn** [ngOfficeUIFabric/ng-officeuifabric#437]
I have a list using
<uif-list uif-item-select-mode="single" ...>

There are a bunch of <uif-list-item>, and a few of them need to be visible but not-selectable (hence disabled). I tried ng-disabled, disabled etc but it doesnt work? Do we support that?

Thanks

**Comment by andrewconnell** [comment]
No, the library doesn't support that use case. We try to follow the same things that the official Office UI Fabric supports and this is not one of those cases.
