### ISSUE TITLE
uif-table scrollable table body

### ISSUE THREAD

**Issue by draconnus** [ngOfficeUIFabric/ng-officeuifabric#451]
If I wish to have a scroll-able table body in a fixed size panel, I have to add `display: block` to uif-table-body. This is due to `uif-table-body` being inline element by default (as suggested by @waldekmastykarz )

If this can't or won't be change, maybe documentation should have an example with scroll-able body.

Codepen example:
http://codepen.io/dspery/pen/PbLPBK

**Comment by andrewconnell** [comment]
Respectfully I don't see what the action item is here. Need more info... please share what would be expected and what you think is wrong... or suggest a solution. 

What your codepen shows is that you can achieve what you're looking to do... so to me, this I can't see what the action item is.

**Comment by draconnus** [comment]
I'd just extend documentation with additional example if you think it can be helpful.
Documentation seems a bit basic.

**Comment by andrewconnell** [comment]
> Documentation seems a bit basic.

That's true... if we have a bug / lack of functionality, then we can act on that. But if it's an issue related to just showing how to use it with a common use case, then that works. IMHO, this one example doesn't really warrant another demo in the repo. In the year this project has been out there, this is the first time it's come up. 

Maybe if you created a separate demo... see the other directives to see how they have more than just a single `demo` folder for edge cases. 

Is that something you'd like to tackle? If so, just a heads up... I'm working on merging in #454 right now that will add extra linting to the JS used in demos, so you might want to wait until that gets merged in if you will have any code in your demo / just rebase your fork & issue branch off `dev` when that gets merged.

**Comment by draconnus** [comment]
Sure, I'll wait for merge.
From discussion on slack I got impression that maybe this was wanted. Nevertheless I'll close the issue. Thx for responses.
