### ISSUE TITLE
Support for the Nav Component

### ISSUE THREAD

**Issue by panigrah** [ngOfficeUIFabric/ng-officeuifabric#460]
Hi,
I am unable to find the Nav Component as described here https://dev.office.com/fabric#/components/nav

Looking for a vertical menu bar.

thanks

**Comment by andrewconnell** [comment]
This library was based on the first version of Fabric (MDL1) which is the Office UI Fabric v2.6.x release branch. That version does not include the nav component and thus, this version of the library won't / can't implement it as we don't ship CSS, just JS... hence why I'm marking this as _wontfix_ and closing the issue.

#### More info...
In version 3 of Office UI Fabric, they updated their design language (MDL2)... I think that version introduced this component. We have plans to update our library to MDL2 (fabric v3+) for Angular 1 as well as implement the library for Fabric v3 & Angular 2... but those are future projects.

See #405 for more info...

**Comment by andrewconnell** [comment]
BTW... this isn't being dismissive... when we wrap this project up & move onto the next two phases for Fabric v3 (MDL2) for Angular 1 & Angular 2, we'll take stock of what Fabric controls there are & make sure we have coverage for them in our library. The goal is to have 100% parity between the version of Fabric & ngOfficeUIFabric... once that's done, I'm personally interested in new components as well... the big ones being adding layout controls as the fabric team @ Microsoft, regardless of the amount of requests & feedback, they just won't entertain those controls.
