### ISSUE TITLE
People picker - disabled

### ISSUE THREAD

**Issue by angex** [ngOfficeUIFabric/ng-officeuifabric#461]
http://ngofficeuifabric.com/demos/uifPeoplePicker/
'All demos based on ngOfficeUIFabric v0.13.1'

People Picker - disabled
Should it work so that if you first search and select one or more people and then disable the field - you should not be able to click the x to remove items from the picker list?

### Expected Behavior
When disabled you should not be able to remove items

### Actual Behavior
When disabled x will remove items from people picker

**Comment by andrewconnell** [comment]
Good catch... doesn't look like the intended behavior.
