### ISSUE TITLE
uif-choicefield-option not selected after load

### ISSUE THREAD

**Issue by marbetschar** [ngOfficeUIFabric/ng-officeuifabric#462]
I've added a `uif-choicefield-group` with multiple `uif-choicefield-option`'s on my page as follows:

```
<uif-choicefield-group ng-model="form.doccacc">
    <uif-choicefield-group-title><label class="ms-Label">Kundenzugriff</label></uif-choicefield-group-title>
	
    <uif-choicefield-option uif-type="radio" value="true">Ja</uif-choicefield-option>
    <uif-choicefield-option uif-type="radio" value="false">Nein</uif-choicefield-option>
</uif-choicefield-group>
```

and this is how the corresponding controller looks like:

```
.controller('appController',function($scope){
    $scope.form = {
        doccacc: false
    };
})
```

### Expected Behavior
After page load, the corresponding `uif-choicefield-option` should be preselected:
![expected](https://cloud.githubusercontent.com/assets/392542/21986191/cc2a9ba0-dbfe-11e6-8d31-91a48af4b64d.png)

### Actual Behavior
None of the `uif-choicefield-option`'s are selected:
![actual](https://cloud.githubusercontent.com/assets/392542/21986213/dc789d9a-dbfe-11e6-8649-fb6159a7ed64.png)

**Comment by ericivarsson** [comment]
Hi @marbetschar,

Looks like the ui-choicefield-group expects a string value for the ng-model binding.
When setting the value to doccacc: "false" the correct option is selected on init:
```
$scope.form = {
      doccacc: 'false'
};
```

I´m not sure if this is the expected behavior or a bug and I haven´t looked deeper into creating a fix but from having a quick look at the current source I do believe it could support Boolean values with a few small changes to the setViewValue and getViewValue functions.

**Comment by andrewconnell** [comment]
Not sure it's a bug, but if that is the case @ericivarsson then we should check if the value passed in is a valid boolean value and respect it, not requiring a text value. IMHO it should expect a boolean, not a string. Need to investigate further...

**Comment by ericivarsson** [comment]
The docs at https://docs.angularjs.org/api/ng/input/input%5Bradio%5D states that `value` only supports string values and that you should use ng-value instead for non-string values like boolean in this case.

I´ve verified that this component works as expected when using ng-value for the uif-choicefield-option elements.

What do you think @andrewconnell, not a bug then right? Perhaps update the demo-page with this information?

@marbetschar using ng-value like this should solve your problem:
`
<uif-choicefield-option uif-type="radio" ng-value="true">Ja</uif-choicefield-option>
<uif-choicefield-option uif-type="radio" ng-value="false">Nein</uif-choicefield-option>`

**Comment by andrewconnell** [comment]
Agreed... good catch @ericivarsson

**Comment by marbetschar** [comment]
@ericivarsson this indeed solved my problem! Thank you both very much for this hint!! Updating the demo page would be fantastic!
