### ISSUE TITLE
BUG and A FIX

### ISSUE THREAD

**Issue by San-Jeevan** [ngOfficeUIFabric/ng-officeuifabric#465]
Dropdown doesnt set value on the view to be the selected value.

faulty line:
instanceElement.find('span').html()

 instanceElement
	            .on('click', function (ev) {
	            scope.$apply(function () {
	                **dropdownController.setViewValue(instanceElement.html(), attrs.value, ev);**
	            });
	        });

**Comment by andrewconnell** [comment]
Can you be more specific where this is? Is this in the source / demo? Specific line number & file would be helpful ;) or even a PR would be really helpful... ;)

**Comment by Rus7am** [comment]
I guess this is the same problem I've just [experienced](http://codepen.io/Rus7am/pen/vgrpaz) with AngularJS **1.6.0/1**: no selected value is shown. Works **fine** with **1.5.9**

If I update **angular** dependency in the source code to **1.6.1** (in package.json) I get **19 failed tests**.

**Comment by andrewconnell** [comment]
@Rus7am - We're aware of that issue with upgrading to 1.6.1... see #431. There were some jQuery updates in that version of Angular that impact our tests, but not our underlying codebase. However we won't rev until all tests pass so we need to fix that issue...

**Comment by andrewconnell** [comment]
Closing this issue as the OP didn't follow up with more detail & can't find the code they reference or the exact problem. Please submit a repo per the issue template instructions if you want to resubmit.
