### ISSUE TITLE
Incomplete checkin of pull request #464

### ISSUE THREAD

**Issue by emilverwoerd** [ngOfficeUIFabric/ng-officeuifabric#468]
Due to the multiple commits it was forgotten to update the spec file 'tableDirective.spec.ts' this issue is to still incorporate those changes.

**Comment by andrewconnell** [comment]
Merged to `dev` branch in 139f653cd882cacedfea5a097223577a9dab5f59. Will get merged into `master` when we bump for next rollout. Not necessary to bump for test update.
