### ISSUE TITLE
People picker single mode

### ISSUE THREAD

**Issue by Rus7am** [ngOfficeUIFabric/ng-officeuifabric#473]
I'd like to be able to select **only one person** in people picker. I think the simplest implementation would be to change the current selected person when you select another one.

Probably this mode should be enabled by special attribute (**single**?). 

### Expected Behavior
Allow only one person can be selected. Change current person when another one is selected.

### Actual Behavior
Multiple people can be chosen. When a person is selected it is added to the selected list.

**Comment by andrewconnell** [comment]
While there's no match for this in the ReactJS version (https://dev.office.com/fabric#/components/peoplepicker), still a nice feature to have but on the backlog.

**Comment by juliemturner** [comment]
I just did a [blog post](http://wp.me/p7UKup-5v) on using the People Picker in SharePoint. I found a hacky workaround for this issue using a $watchCollection... that said, I agree it would be a nice feature.

**Comment by andrewconnell** [comment]
Implemented in v0.16.0
