### ISSUE TITLE
[uif-table] uif-sort-order icon issue on Angular 1.6.x

### ISSUE THREAD

**Issue by vi-verrone** [ngOfficeUIFabric/ng-officeuifabric#475]
It seems that since Angular 1.6 the `ng-transclude` directive is not wrapping anymore the transcluded content with a `span` element (as you can see here: https://github.com/angular/angular.js/issues/15223).
For this reason the `uif-table` component has a strange behavior when setting `uif-sort-by` by duplicating the sorting icon when clicked more than once (plunker: https://plnkr.co/edit/148dylPMR5U2OOfsA6OG?p=preview)

I'm planning to solve this issue and submit the pull request really soon

**Comment by andrewconnell** [comment]
I can't see the issue in the plunker you've provided. Can you please clarify what's wrong and how to dupe it?

BTW, we don't support Angular 1.6+ yet. See #431 ... there were changes with how Angular uses jQuery and it's caused a lot of our tests to fail... that needs to be resolved before we can move to 1.6.

So... if you can clarify / update the issue with a Plunker that shows the issue & also show that the fix doesn't impact Angular 1.5, we can merge the fix in.

**Comment by vi-verrone** [comment]
Ok, i updated the plunkr leaving only the 'Sorting table' example. You can dupe the issue by  clicking on the first header 'File name', in a first approach you can already see that the sorting icon is freezed to be caret-down, then when you click another Header with sorting feature (like 'Modified') and after that you click again 'File name' you have the duplicated sorting icon. As already said, this is caused due an update of ng-transclude from Angular 1.6.x and i already fixed this. You can see the fix on the Pull Request i sent, wiht link to current issue, fix on Angular 1.6.x and also Angular 1.5.2 (to show that the changes has no impact on version of Angular before 1.6.x)
