### ISSUE TITLE
Do it work with Angular 2+?

### ISSUE THREAD

**Issue by biapar** [ngOfficeUIFabric/ng-officeuifabric#478]
Do it work with Angular 2+?

**Comment by andrewconnell** [comment]
No, this is an Angular 1 implementation at the moment. Angular 2 is on our roadmap.

**Comment by schmkr** [comment]
@andrewconnell Can we view this roadmap somewhere? Has development already started? Can we track progress somewhere or could you give a rough estimate on when to expect this?

**Comment by spcfran** [comment]
Perhaps this could be made clearer on some places (particularly the project description and the  `README.md`) by using **AngularJS** instead of **Angular**, which is how Angular2+ is meant to be known onwards.

**Comment by andrewconnell** [comment]
Agreed @spcfran ... the docs could definitely be updated. Care to log this as an issue and take ownership contributing to the docs?

**Comment by andrewconnell** [comment]
@schmkr Sorry for the delay... while I said it above, there isn't an official roadmap... we're in a state of flux. The closest we have is here: https://github.com/ngOfficeUIFabric/ng-officeuifabric/issues/405

But even that is outdated...
