### ISSUE TITLE
uif-searchbox is not working with ngOfficeUiFabric v0.14.0

### ISSUE THREAD

**Issue by bhosalemahesh899** [ngOfficeUIFabric/ng-officeuifabric#479]
uif-searchbox is not working with ngOfficeUiFabric v0.14.0

with ngOfficeUiFabric v0.14.0
https://jsfiddle.net/bhosalemahesh899gmailcom/owv9fw4f/14/

with ngOfficeUiFabric v0.11.0
https://jsfiddle.net/bhosalemahesh899gmailcom/owv9fw4f/15/

**Comment by jjczopek** [comment]
Hi @bhosalemahesh899 
As of now, `uif-searchbox` component uses ng-model to set & retrieve value.
I have made necessary correction in the demo.

**Comment by bhosalemahesh899** [comment]
Thank you jjczopek
