### ISSUE TITLE
People Picker close event not firing

### ISSUE THREAD

**Issue by vrndeva** [ngOfficeUIFabric/ng-officeuifabric#490]
This is the sample code:  uif-person-close="removeClicked"

On my HTML:
<uif-people-picker` uif-people="getUsers" ng-model="Test" uif-type="compact"  uif-person-close="removeClicked"  uif-selected-person-click="personClicked"  data-ng-click="getSelectedGetUsersId(user)" uif-search-delay="300" placeholder="Search for people">
  
<uif-people-search-more>
        <uif-secondary-text>Showing {{asyncgetUsersResults.length}} results</uif-secondary-text>
        <uif-primary-text uif-search-for-text="You are searching for: ">Search organization people</uif-primary-text>
  </uif-people-search-more>
</uif-people-picker>

On my Controller:
 $scope.removeClicked = function ()
         {
             alert('Remove Clicked');
         }

### Expected Behavior
Supposed to Call removeClicked event in the controller.

### Actual Behavior
Nothing happens

**Comment by vrndeva** [comment]
The issue is when I add any person and click on Close after adding the person.

**Comment by andrewconnell** [comment]
Do you have a repo like a jsfiddle you can share to make it easier to see the issue @vrndeva ?

**Comment by andrewconnell** [comment]
This isn't an event we currently support... I think you're looking for the event `removePersonFromSelectedPeople` that we have on the scope. Refer to the source of the scope's interface for this: https://github.com/ngOfficeUIFabric/ng-officeuifabric/blob/master/src/components/peoplepicker/peoplePickerDirective.ts#L180-L220
