### ISSUE TITLE
Upgrading Angular JS to version 1.6.x causes the uif-dropdown to display incorrectly

### ISSUE THREAD

**Issue by kbrimington** [ngOfficeUIFabric/ng-officeuifabric#491]
Upgrading Angular JS to version 1.6.x causes the uif-dropdown directive to break.

### Expected Behavior

Selecting an option in the uif-dropdown should update the model and also update the display value presented within the drop down.

### Actual Behavior

The initial value of the dropdown is presented correctly. Selecting an option in the uif-dropdown does update the model correctly, but does not update the display value. No errors are produced in the console.

![image](https://cloud.githubusercontent.com/assets/21696007/25500027/af8e2f66-2b4a-11e7-9e2c-ddcd5e29cf30.png)

### Steps to Reproduce Behavior

The plunker below demonstrates the issue. Changing the version of AngularJS to 1.5.11 results in normal behavior. Changing the version of AngularJS to 1.6.0, 1.6.1, 1.6.2, 1.6.3, or 1.6.4 results in the symptoms described above.

http://plnkr.co/edit/CWw6jPeDo8wVenvZwNJu

**Comment by nightullr** [comment]
The issue no longer occurs if you use the most recent version of ngOfficeUIFabric - it was recently updated to 0.15.0, which fixed the issue for me when using AngularJS 1.6+. See pull request #483 .

**Comment by andrewconnell** [comment]
@nightullr is correct... see this fork of your plunk. All I did was replace your version of ngOfficeUIFabric with the v0.15.0 copy in CDNJS: 

http://plnkr.co/edit/d7k83IQSDuY9XZqs5eH4?p=preview

**Comment by kbrimington** [comment]
Ah. I see. Thanks for the help!
