### ISSUE TITLE
How can i have two tables on same page with different row-select-mode

### ISSUE THREAD

**Issue by gonadn** [ngOfficeUIFabric/ng-officeuifabric#495]
HI

Iam using uif-table component from ng-office-ui-fabric in my application.
And i have problom understanding how i can seperate select-mode behavior on my tables.
I have two table on the page, table on left side have to be with multiple select mode, and table on rigth side have to be with "none" select mode. 

My problom is that if i set my table on rigth side to uif-row-select-mode="none", then both tables left and rigth side get select mode to "none". 

What i am trieng to figure out is how i can have seperate behaviour on my tables?

**Comment by andrewconnell** [comment]
Hey @waldekmastykarz do you recall if this is supported or how it's done? I know it's been a while since you built the control...

**Comment by waldekmastykarz** [comment]
It seems like at this moment we're not supporting it as we keep track of it on the parent scope.

**Comment by andrewconnell** [comment]
@gonadn Looks like that isn't supported at the moment.
