### ISSUE TITLE
uif-list is missing in ngOfficeUiFabric.min.js v.0.2.0

### ISSUE THREAD

**Issue by michal-husak** [ngOfficeUIFabric/ng-officeuifabric#496]
I am trying to use [https://cdnjs.cloudflare.com/ajax/libs/ngOfficeUiFabric/0.2.0/ngOfficeUiFabric.min.js](https://cdnjs.cloudflare.com/ajax/libs/ngOfficeUiFabric/0.2.0/ngOfficeUiFabric.min.js) and there is **uif-list** missing. Therefore I can't use [uif-list directive](http://ngofficeuifabric.com/demos/uifList/) in this version.

Did you forget to export it?

**Comment by andrewconnell** [comment]
No... it didn't exist in v0.2.0... that's a VERY old version of the library. Use 0.15.1 for latest. Looks like you grabbed the link from the homepage of the repo... that's just an example.

See: 
https://cdnjs.com/libraries/ngOfficeUiFabric
