### ISSUE TITLE
Can't find icon ShowResults

### ISSUE THREAD

**Issue by Mcdull731** [ngOfficeUIFabric/ng-officeuifabric#509]
Having an issue? Please give us as much information as possible, provide repo steps & ideally a [plunker](https://plnkr.co/), [jsfiddle](https://jsfiddle.net/) or [CodePen](https://codepen.io) that demonstrates the issue.

Not an issue? Feel free to delete this template & create an issue from scratch.

**Comment by andrewconnell** [comment]
This library takes a dependency of the MDL1 of the Office UI Fabric which is the 2.6.3 branch. That branch does not include this icon as you can see here: https://github.com/OfficeDev/office-ui-fabric-core/blob/release/2.6.3/src/sass/Fabric.Icons.Output.scss
