### ISSUE TITLE
Command button does not display text inside <uif-button /> tag

### ISSUE THREAD

**Issue by Rus7am** [ngOfficeUIFabric/ng-officeuifabric#510]
### Expected Behavior
Text inside `<uif-button />` tag displayed when **uif-type** attribute set to **command**

### Actual Behavior
Text inside `<uif-button />` tag is removed if **uif-type** attribute is set to **command** (see the [pen](https://codepen.io/Rus7am/pen/QOLzVm/)).

**Comment by andrewconnell** [comment]
You're using an old version of Angular that this library doesn't support. You must use a version 1.6+. When I updated your codepen to use 1.6.4, it worked.

**Comment by Rus7am** [comment]
Oh, apologies, my mistake.
