### ISSUE TITLE
AngularJS vs Angular naming confusion

### ISSUE THREAD

**Issue by Splaktar** [ngOfficeUIFabric/ng-officeuifabric#511]
Hello. Thank you for your efforts building Fabric UI for AngularJS!

I just noticed some very confusing inconsistencies on the following sites:
https://github.com/ngOfficeUIFabric/ng-officeuifabric
https://developer.microsoft.com/en-us/fabric#/angular-js
http://ngofficeuifabric.com/
https://developer.microsoft.com/en-us/fabric

There are quite a number of references to Angular, however this project currently only supports AngularJS. This will become more confusing as you create another repo (I assume this) to handle support for Angular. 

Finally, for clarity:
- AngularJS = versions 0 through 1.x
- Angular = versions 2.x+ (4, 5, 6, etc increasing approximately every 6 months)

More details can be found on this [here](http://angularjs.blogspot.com/2017/01/branding-guidelines-for-angular-and.html).

Btw, I'm quite happy to hear that you will be [starting work on support Angular soon](https://www.google.com/url?q=http://g.co/ng/weekly-notes&sa=D&ust=1511338536252000&usg=AFQjCNGR3-LaJ67Bgh-BN8C8T4qWA5FwaA)! Things are very stable and the [CDK](https://material.angular.io/cdk/categories) makes a great place to start.

**Comment by andrewconnell** [comment]
Fully understand all that... and in the properties we own & have control over (those you list in your issue that do not have `*.microsoft.com` in them) the version names are correct and only refer to AngularJS.

However, we can't control what Microsoft does and they have mixed AngularJS and Angular together in many places creating this confusion. We can only control our messaging. 

This project is not affiliated with MSFT in any way... 100% community driven.
