### ISSUE TITLE
Add support for selecting rows in table

### ISSUE THREAD

**Issue by waldekmastykarz** [ngOfficeUIFabric/ng-officeuifabric#61]
Extend table with support for sorting using the following specs:
- [x] table supports three row selection modes: _none_, _single_ and _multiple_
- [x] table selection mode is set using the `uif-row-select-mode` attribute on the `uif-table` directive
- [x] clicking on the header row doesn't do anything
- [x] selected items can be retrieved using the `table.selectedItems` property
- [x] for `uif-row-select-mode="none"`:
  - [x] cursor is set to regular pointer using inline CSS styles
  - [x] clicking a row doesn't do anything
  - [x] clicking the `uif-table-row-select` directive doesn't do anything
- [x] for `uif-row-select-mode="single"`:
  - [x] cursor is set to hand (already set by Office UI Fabric)
  - [x] clicking an unselected row selects that row and deselects any other selected row
  - [x] clicking an already selected row deselects that row
  - [x] clicking the `uif-table-row-select` directive in the header row doesn't do anything
  - [x] clicking the `uif-table-row-select` directive in regular rows has the same effect as clicking on the row
- [x] for `uif-row-select-mode="multiple"`:
  - [x] cursor is set to hand (already set by Office UI Fabric)
  - [x] clicking an unselected row selects that row~~; additionally it sets the `allRowsSelected` property on the table scope to `false`~~
  - [x] clicking an already selected row deselects that row
  - [x] if not all rows are selected, clicking the `uif-table-row-select` directive in the header row selects all rows
  - [x] if all rows are selected, clicking the `uif-table-row-select` directive in the header row deselects all rows

**Comment by andrewconnell** [comment]
The way I read this is that the _user_ dictates single / multiselect... it should be controlled by the _developer_, not the _user_. 

I think there should be something about enabling / disabling multirow selection within the opening `<uif-table />` directive. This way when you select a row by clicking anywhere on it it will either add to the selection or toggle existing selected rows based on the setting that the developer set.

**Comment by waldekmastykarz** [comment]
Don't you think this might be confusing and could lead to two tables being implemented differently in different applications offering users different user experiences? Is there perhaps an office application that uses tables that we could take a look at to see how it's working?

**Comment by jjczopek** [comment]
I think the following when it comes into row selecting:
- developer should define whether users can select rows or not - on table level (like @andrewconnell suggested).
- if selecting is enabled, developer defines if it's single- or multi-select.
  - if single-select is enabled, when user clicks row, this row gets selected and other row is deselected
  - if multi-select is enabled, when user clicks row, this row is appended to the list of selected rows or removed from that list if it was selected before (toggle)

I think that's intuitive and simple.

I have also found grid implementation for Angular Material - [md-data-grid](https://github.com/daniel-nagy/md-data-table#row-selection) - it looks like there it is defined per row (eg. with ng-repeat) whether the row is selectable.

**Comment by andrewconnell** [comment]
@waldekmastykarz I don't think it would be confusing... sure the two tables might behave differently on selection, but how is that any different from a single / multi select dropdown control? It isn't. It's worse if I as the developer have to keep unselecting something because the user selected a row already and I only allow for them to select one.

**Comment by waldekmastykarz** [comment]
Support for both single- and multiselect scenarios would be useful indeed. What if we would do it this way:
- if you want support for multiselect, you include the `uif-table-row-select` directive in both the header and regular rows. Clicking on the rendered control in the header toggles selection of all rows and clicking it in a regular row toggles selection of that particular row
- if you want support for single row selection, you don't include the `uif-table-row-select` directive in your table. Clicking on a row selects that row and deselects any other selected row. This works the same for single- and multiselect scenario's.

I've had a look at it and saw that this is how table is implemented in OneDrive. What do you say we chose the same approach?

**Comment by andrewconnell** [comment]
... and if you don't want any selection, you don't use the `uif-table-row-select` at all, correct?

**Comment by waldekmastykarz** [comment]
In my suggestion I assumed that `uif-table-row-select` would be used for selecting rows in multiselect scenarios. In single select scenarios rows would be selected by clicking on the row. If we wanted to support disabling selecting rows altogether we would need additional property (eg. `uif-disable-row-selection` on the `uif-table` directive). Additionally we would need to override the standard Office UI Fabric CSS which automatically changes cursor to hand on row hover. If we don't allow for selecting rows, cursor should be the standard pointer to avoid confusion.

**Comment by andrewconnell** [comment]
IMHO I think no selection (and just use the table for displaying data) should be the default. Then have options for selecting. Maybe a `uif-table-row-selectMode` = `"none (default) | single | multiple"` on the `uif-table` directive

**Comment by waldekmastykarz** [comment]
For `selectMode = single` are we okay with the `uif-table-row-select` directive in the header row not to do anything (whereas for `selectMode = multiple` it toggles selection of all table rows)?
For `selectMode = none`: since we're not shipping any CSS, are we okay with inline overriding of the cursor to _pointer_ to avoid confusion (by default row:hover changes the cursor to _hand_ which suggests that the row can be clicked)?

**Comment by jjczopek** [comment]
I agree with both points.

**Comment by andrewconnell** [comment]
LGTM... BTW I'm not against shipping CSS in our library if its warranted for anything. The only concern I have with an inline style is if someone would want to change the cursor. If they did, there's really no way to do that with an inline style.

**Comment by waldekmastykarz** [comment]
@andrewconnell good point. How about we go with inline styles initially and see if anyone raises it as a blocking issue for their scenario? If they do we could always change it to use external styles.

**Comment by andrewconnell** [comment]
works for me

**Comment by waldekmastykarz** [comment]
:+1:

**Comment by waldekmastykarz** [comment]
Based on the previous discussions I've updated the specs in the first comment

**Comment by andrewconnell** [comment]
WOW... that's a lot of checkboxes... you sure your next control isn't going to be #16 ? :smirk:

**Comment by waldekmastykarz** [comment]
;)

**Comment by waldekmastykarz** [comment]
Looking at the number of these checkboxes, who would've thought implementing row selection in a table would be so complex ;-)
