### ISSUE TITLE
Add support for sorting table using column headers

### ISSUE THREAD

**Issue by waldekmastykarz** [ngOfficeUIFabric/ng-officeuifabric#62]
Add support for sorting table using column headers based on the following specs:
- [x] sorting is supported only for columns where the header cell has the `uif-sortable` attribute set to `true`
- [x] default sorting order is ascending. Clicking the header cell again toggles sorting order. Sorting order is tracked in a property on the header cell
- [x] sorting direction is indicated using an arrow icon appended to the header cell which is currently used for sorting
- [x] clicking on a header cell resets sorting on other columns. It is possible to sort the table using only one column

**Comment by andrewconnell** [comment]
:+1:

**Comment by waldekmastykarz** [comment]
I've included a slight change in the specs: instead of using the `uif-sortable="true"` attribute, we use `uif-order-by="property"` where the property is the name of the property used to sort data.

**Comment by aaronhamilton** [comment]
This is great stuff! 
One thing I can't figure out: how to set default sort for first render. When my page loads, it just loads the data based on data item index. Is there a way to specify a default sort field and direction?
Thanks!
Aaron

**Comment by waldekmastykarz** [comment]
Thanks! Have you checked out the sample at https://github.com/ngOfficeUIFabric/ng-officeuifabric/blob/master/src/components/table/demoSortableColumns/index.html? Default sorting is passed through the ng-repeat directive with the initial data set.

**Comment by aaronhamilton** [comment]
I don't see default sort in your ng-repeat, but I was able to get it
working:

<uif-table-row ng-repeat="data in vm.currentRows | orderBy:'FullName' |
orderBy:table.orderBy:!table.orderAsc">

Can you add the default orderBy to your example?

Aa

**Comment by aaronhamilton** [comment]
I take it back.. my solution is not default sorting...

**Comment by aaronhamilton** [comment]
My bad. It _is_ working :-)
