### ISSUE TITLE
Enforce each custom attribute have a uif- prefix?

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#73]
Seeking input... we had casually set a rule that any directive that created a custom attribute would have that attribute prefixed with our namespace `uif-`. However I'm seeing a lot of inconsistency in the implementations. 

For instance, on the icon you set the type of icon you want to use. That's done with:

``` html
<uif-icon uif-type="plus" />
```

But I see other components that aren't doing that like the textfield where you can say if you want to use the underlined style:

``` html
<uif-textfield label="this is the label" underlined />
```

When I look at Angular Material, they favor the latter approach (no prefix on attributes).

Before we ship our first release, I'd like to have some consistency set... and I'm happy to be the one to fix all existing directives & demos... not a hard thing for me to do before we ship. I just think we should have some consistency... either DON'T require it or require that it's only used for elements and not attributes.

Thoughts? I'm sort of in favor of the latter (no prefix), more concise, style.

**Comment by andrewconnell** [comment]
Seeking input from @ngOfficeUIFabric/ngofficeuifabric-members

**Comment by jigargandhi** [comment]
Angular material prefers to have md-\* prefix to custom attributes. 
For example the [icon](https://material.angularjs.org/latest/api/directive/mdIcon) directive attribute has `md-svg-icon` attribute that specifies the icon

Another example is [autocomplete](https://material.angularjs.org/latest/api/directive/mdAutocomplete), it has the following html specified

``` html
 <md-autocomplete md-selected-item="selectedItem" md-search-text="searchText" md-items="item in getMatches(searchText)" md-item-text="item.display">
 <span md-highlight-text="searchText">{{item.display}}</span>
</md-autocomplete>
```

You can see several instances of custom attributes with `md-` prefix. 

Shouldn't we be following the same pattern for this library?

**Comment by ghost** [comment]
I'd say for custom attributes, use a prefix. Icon type = custom => prefix.
Text value = default => no prefix

E.g. label-off and label-on in the toggle are custom, and should get a prefix too.

**Comment by jigargandhi** [comment]
Might be confusing for users as some attributes are with prefix and some are without

**Comment by andrewconnell** [comment]
@rolandoldengarm so that's how I have been thinking about it, but I'm starting to wonder. I looked at what Material was doing. 

@jigargandhi Good find... I was looking at others like [card](https://material.angularjs.org/latest/demo/card) and noticed some flex & layout attributes that were not familiar to me nor in any list of valid HTML attributes. I noticed Material does use the **md-** prefix a lot but it didn't seem consistent.

**Comment by waldekmastykarz** [comment]
I would opt for prefixing custom attributes. In cases when things don't work as expected makes it easier to figure out what is being handled by the directive and what isn't.

**Comment by jjczopek** [comment]
I think we should prefix our custom attributes. Attributes that are well-known HTML attributes or which are standard Angular directives, should not be prefixed, but their purpose in specific component should be consistent with initial purpose of the attribute, e.g `disabled` should always mean that input element is disabled.

**Comment by andrewconnell** [comment]
Thanks for the input everyone... I think there's a consensus then.

So there are a few controls that need to get updated (I can do these before we cut the release):
- [x] **textfied**: `underline` => `uif-underline`
- [x] **textfield**: `label` => uif-label`
- [x] **textfield**: `description` => uif-description`
- [x] **toggle**: `label-off` => `uif-label-off`
- [x] **toggle**: `label-on` => `uif-label-on`
- [x] **toggle**: `text-location` => `uif-text-location`

**Comment by ghost** [comment]
:+1:
