### ISSUE TITLE
Standardizing error messages from directives in the console

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#88]
I'm adding some logic to the 'uif-icon' directive to check if the developer requested an invalid icon that isn't supported within the fabric fonts. If they didn't I'm logging an error to the console... Which brings up: how should we standardize this?

Long term I like how angular does it where they link to their site, but that's long term. I think now we just do something like:

'''
Error [ngOfficeUiFabric] fully-qualified-module - error summary: error detail (see more: link to MD file in master branch of repo located within the directive's folder / beside the directive itself)
'''

Seeking input @ngOfficeUIFabric/ngofficeuifabric-members

**Comment by s-KaiNet** [comment]
For me all good

**Comment by andrewconnell** [comment]
Here's how it renders:

![image](https://cloud.githubusercontent.com/assets/2068657/12323475/81601204-ba89-11e5-88ed-5714f33cf18e.png)

**Comment by jjczopek** [comment]
Looks nice. Should we consider this kind of validation for every _typed/enumerated_ option, e.g. in spinner component I can have following logic:
- if `uif-spinner-size="large"` - spinner is considered large
- if `uif-spinner-size="small"` or `uif-spinner-size` without value or anything different than small or large, then I render small spinner.

Should I then consider only `"small"` and `"large"` as valid and throw error any other?

**Comment by ghost** [comment]
Looks good to me too. We will probably need more validation.

**Comment by andrewconnell** [comment]
@jjczopek Personally I think so... anything that has deterministic options, if one out-of-bounds thing is thrown, it should throw an error in the log.

**Comment by waldekmastykarz** [comment]
:+1:

**Comment by andrewconnell** [comment]
closing the loop... used angular's `$log` instead of `console.log` ... the main demo shows it now & you can see it here in dev for now until next drop: https://github.com/ngOfficeUIFabric/ng-officeuifabric/blob/dev/src/components/icon/iconDirective.ts#L69-L74
